### ISSUE TITLE
AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLSv1'

### ISSUE THREAD

**Issue by zjykzj** [pyca/pyopenssl#1029]
This problem is so outrageous that I can't find any information on the Internet.  I write it down and hope others can solve it as soon as possible

## Problem

Using Anaconda Python 3.8/3.9

```
$ conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia
Traceback (most recent call last):
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 81, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "/home/zj/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/cli/main_install.py", line 8, in <module>
    from .install import install
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/cli/install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/core/index.py", line 12, in <module>
    from .package_cache_data import PackageCacheData
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/core/package_cache_data.py", line 14, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/core/path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/gateways/connection/__init__.py", line 21, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "/home/zj/miniconda3/lib/python3.9/site-packages/requests/__init__.py", line 101, in <module>
    from urllib3.contrib import pyopenssl
  File "/home/zj/miniconda3/lib/python3.9/site-packages/urllib3/contrib/pyopenssl.py", line 90, in <module>
    ssl.PROTOCOL_TLSv1: OpenSSL.SSL.TLSv1_METHOD,
AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLSv1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zj/miniconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 152, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1126, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1137, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1207, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/cli/main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/core/index.py", line 12, in <module>
    from .package_cache_data import PackageCacheData
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/core/package_cache_data.py", line 14, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/core/path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "/home/zj/miniconda3/lib/python3.9/site-packages/conda/gateways/connection/__init__.py", line 21, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "/home/zj/miniconda3/lib/python3.9/site-packages/requests/__init__.py", line 101, in <module>
    from urllib3.contrib import pyopenssl
  File "/home/zj/miniconda3/lib/python3.9/site-packages/urllib3/contrib/pyopenssl.py", line 90, in <module>
    ssl.PROTOCOL_TLSv1: OpenSSL.SSL.TLSv1_METHOD,
AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLSv1'
```

## Solution

I try to reinstall or upgrade requests / urllib3 / pyopenssl using pip,  doesn't work.  Finally, I tried to install it through apt install (by the way, i'
m working in Ubuntu), the problem is solved

```
$ sudo apt install openssl
[sudo] password for zj: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be upgraded:
  openssl
1 upgraded, 0 newly installed, 0 to remove and 68 not upgraded.
Need to get 620 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 openssl amd64 1.1.1f-1ubuntu2.4 [620 kB]
Fetched 620 kB in 3s (194 kB/s)                      
(Reading database ... 151393 files and directories currently installed.)
Preparing to unpack .../openssl_1.1.1f-1ubuntu2.4_amd64.deb ...
Unpacking openssl (1.1.1f-1ubuntu2.4) over (1.1.1f-1ubuntu2.3) ...
Setting up openssl (1.1.1f-1ubuntu2.4) ...
Processing triggers for man-db (2.9.1-1) ...
```

**Comment by alex** [comment]
You're getting an `AttributeError` on the `ssl` module, not pyOpenSSL, and the exception is coming from `urllib3`, not pyOpenSSL.
