### ISSUE TITLE
Error on running ./examples/idp.py  and ./examples/sp.py 

### ISSUE THREAD

**Issue by simsolTech** [pyca/pyopenssl#1141]
**I was getting the following errors**:

Traceback (most recent call last):
  File "/Users/deepaktr/MyDocuments/saml/flask-saml2/./examples/idp.py", line 7, in <module>
    from flask_saml2.idp import IdentityProvider
  File "/Users/deepaktr/MyDocuments/saml/flask-saml2/flask_saml2/idp/__init__.py", line 1, in <module>
    from .idp import IdentityProvider
  File "/Users/deepaktr/MyDocuments/saml/flask-saml2/flask_saml2/idp/idp.py", line 6, in <module>
    from flask_saml2.signing import Digester, RsaSha1Signer, Sha1Digester, Signer
  File "/Users/deepaktr/MyDocuments/saml/flask-saml2/flask_saml2/signing.py", line 10, in <module>
    import OpenSSL.crypto
  File "/Users/deepaktr/MyDocuments/saml/flask-saml2/venv/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/Users/deepaktr/MyDocuments/saml/flask-saml2/venv/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1550, in <module>
    class X509StoreFlags(object):
  File "/Users/deepaktr/MyDocuments/saml/flask-saml2/venv/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1570, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

**How I solved**
pip uninstall pyopenssl 
Found existing installation: pyOpenSSL 17.5.0
Uninstalling pyOpenSSL-17.5.0:
  Would remove:
    /Users/deepaktr/MyDocuments/saml/flask-saml2/venv/lib/python3.9/site-packages/OpenSSL/*
    /Users/deepaktr/MyDocuments/saml/flask-saml2/venv/lib/python3.9/site-packages/pyOpenSSL-17.5.0.dist-info/*
Proceed (Y/n)? y
  Successfully uninstalled pyOpenSSL-17.5.0
pip install pyopenssl  
Collecting pyopenssl
  Downloading pyOpenSSL-22.0.0-py2.py3-none-any.whl (55 kB)

**Comment by alex** [comment]
You upgraded the version of cryptography you are using today. Did you read the changelog? https://cryptography.io/en/latest/changelog/#v38-0-0

> Removed several legacy symbols from our OpenSSL bindings. Users of pyOpenSSL versions older than 22.0 will need to upgrade.
