### ISSUE TITLE
cannot import name 'x509' from 'cryptography.hazmat.bindings._rust' 

### ISSUE THREAD

**Issue by yurivict** [pyca/pyopenssl#1157]
The ```veles``` project fails with this message:
```
Traceback (most recent call last):
  File "/usr/local/bin/veles-server", line 23, in <module>
    from veles.server.proto import (create_unix_server, create_tcp_server,
  File "/usr/local/lib/python3.9/site-packages/veles/server/proto.py", line 27, in <module>
    from OpenSSL import crypto
  File "/usr/local/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.9/site-packages/OpenSSL/crypto.py", line 14, in <module>
    from cryptography import utils, x509
  File "/usr/local/lib/python3.9/site-packages/cryptography/x509/__init__.py", line 6, in <module>
    from cryptography.x509 import certificate_transparency
  File "/usr/local/lib/python3.9/site-packages/cryptography/x509/certificate_transparency.py", line 10, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
ImportError: cannot import name 'x509' from 'cryptography.hazmat.bindings._rust' (unknown location)
Process of locally created server finished. Exit code: 1.
NetworkClient: Disconnect.
```

py-openssl-20.0.1 is installed.
py39-cryptography-38.0.1 is installed, which satisfies cryptography>=3.2.
Python-3.9
FreeBSD 13.1

**Comment by alex** [comment]
Can you please provide complete instructions for reproducing from a clean environment? An error like this typically indicates a failed installation.
