### ISSUE TITLE
The new version of pyopenssl shows AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

### ISSUE THREAD

**Issue by linhmeobeo** [pyca/pyopenssl#1177]
Pyopenssl shows the error while installing python3.8 :
File "/home/vsts/work/1/s/.venv/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.crypto
  File "/home/vsts/work/1/s/.venv/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/vsts/work/1/s/.venv/lib/python3.8/site-packages/OpenSSL/crypto.py", line 3268, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

**Comment by reaperhulk** [comment]
Are you sure you're using the latest version of pyOpenSSL? That code is not present in 22.1.0 or 23.0.0.

**Comment by linhmeobeo** [comment]
Indeed I was looking again at the chain of library, it was called from cryptography lib, and linked to sam aws. Version of pyopenssl is 22.0.0.
Found this and they should be linked https://github.com/aws/aws-sam-cli/issues/4527

**Comment by linhmeobeo** [comment]
Its more of aws sam issue

**Comment by SamyOteroGlez** [comment]
I am having this same issue today. 

I created a fresh VM in Digital Ocean (Ubuntu 20.04 LTS), followed the installation instructions for docker. But when I start the containers I get the following:

```
django4my_geonode       | **************************migrations*******************************
django4my_geonode       | Traceback (most recent call last):
django4my_geonode       |   File "/usr/src/my_geonode/manage.py", line 31, in <module>
django4my_geonode       |     execute_from_command_line(sys.argv)
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
django4my_geonode       |     utility.execute()
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
django4my_geonode       |     django.setup()
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
django4my_geonode       |     apps.populate(settings.INSTALLED_APPS)
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 114, in populate
django4my_geonode       |     app_config.import_models()
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/django/apps/config.py", line 301, in import_models
django4my_geonode       |     self.models_module = import_module(models_module_name)
django4my_geonode       |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
django4my_geonode       |     return _bootstrap._gcd_import(name[level:], package, level)
django4my_geonode       |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
django4my_geonode       |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
django4my_geonode       |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
django4my_geonode       |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
django4my_geonode       |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
django4my_geonode       |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/geonode/base/models.py", line 68, in <module>
django4my_geonode       |     from geonode.utils import (
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/geonode/utils.py", line 73, in <module>
django4my_geonode       |     from geonode.storage.manager import storage_manager
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/geonode/storage/manager.py", line 34, in <module>
django4my_geonode       |     from geonode.storage.data_retriever import DataItemRetriever, DataRetriever
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/geonode/storage/data_retriever.py", line 25, in <module>
django4my_geonode       |     import smart_open
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/smart_open/__init__.py", line 34, in <module>
django4my_geonode       |     from .smart_open_lib import open, parse_uri, smart_open, register_compressor  # noqa: E402
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/smart_open/smart_open_lib.py", line 35, in <module>
django4my_geonode       |     from smart_open import doctools
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/smart_open/doctools.py", line 21, in <module>
django4my_geonode       |     from . import transport
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/smart_open/transport.py", line 101, in <module>
django4my_geonode       |     register_transport('smart_open.s3')
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/smart_open/transport.py", line 49, in register_transport
django4my_geonode       |     submodule = importlib.import_module(submodule)
django4my_geonode       |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
django4my_geonode       |     return _bootstrap._gcd_import(name[level:], package, level)
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/smart_open/s3.py", line 17, in <module>
django4my_geonode       |     import boto3
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/boto3/__init__.py", line 17, in <module>
django4my_geonode       |     from boto3.session import Session
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
django4my_geonode       |     import botocore.session
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/botocore/session.py", line 26, in <module>
django4my_geonode       |     import botocore.client
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 17, in <module>
django4my_geonode       |     from botocore import waiter, xform_name
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/botocore/waiter.py", line 18, in <module>
django4my_geonode       |     from botocore.docs.docstring import WaiterDocstring
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/botocore/docs/__init__.py", line 15, in <module>
django4my_geonode       |     from botocore.docs.service import ServiceDocumenter
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/botocore/docs/service.py", line 14, in <module>
django4my_geonode       |     from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/botocore/docs/client.py", line 14, in <module>
django4my_geonode       |     from botocore.docs.example import ResponseExampleDocumenter
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/botocore/docs/example.py", line 13, in <module>
django4my_geonode       |     from botocore.docs.shape import ShapeDocumenter
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/botocore/docs/shape.py", line 19, in <module>
django4my_geonode       |     from botocore.utils import is_json_value_header
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/botocore/utils.py", line 34, in <module>
django4my_geonode       |     import botocore.httpsession
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/botocore/httpsession.py", line 46, in <module>
django4my_geonode       |     from urllib3.contrib.pyopenssl import (
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
django4my_geonode       |     import OpenSSL.SSL
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
django4my_geonode       |     from OpenSSL import crypto, SSL
django4my_geonode       |   File "/usr/local/lib/python3.10/site-packages/OpenSSL/crypto.py", line 3268, in <module>
django4my_geonode       |     _lib.OpenSSL_add_all_algorithms()
django4my_geonode       | AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
```

**Comment by alex** [comment]
The software you are installing has pinned pyOpenSSL to an older version, but is installing the newest cryptography.

It should either upgrade the pyOpenSSL, or downgrade the version of cryptography. (Upgrading pyOpenSSL is preferred.)
