### ISSUE TITLE
PyOpenSSL broken on PyPy 2.2.1 when used with Flask Ad-Hoc SSL

### ISSUE THREAD

**Issue by OOPMan** [pyca/pyopenssl#118]
For the last 9 months or so I've been working on a Flask web application quite happily in PyPy. Recently I've started to dig into securing the application a little more so I decided to try enabling SSL.

After some googling I came across [this](http://kracekumar.com/post/54437887454/ssl-for-flask-local-development) and decided to give it a try.

pyopenssl installed fine in my PyPy 2.2.1 environment and I then proceeded to enable ad-hoc mod in Flask and test.

Flask seemed to start fine but upon trying to load my site I go the following traceback:

```
Traceback (most recent call last):
  File "/home/adamj/Development/Tools/Python/Interpreters/pypy/pypy-2.2.x/x86_64-portable/lib-python/2.7/SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/adamj/Development/Tools/Python/Interpreters/pypy/pypy-2.2.x/x86_64-portable/lib-python/2.7/SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "/home/adamj/Development/Tools/Python/Interpreters/pypy/pypy-2.2.x/x86_64-portable/lib-python/2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/adamj/Development/Tools/Python/Interpreters/pypy/pypy-2.2.x/x86_64-portable/lib-python/2.7/SocketServer.py", line 636, in __init__
    self.setup()
  File "/home/adamj/Development/Tools/Python/Interpreters/pypy/pypy-2.2.x/x86_64-portable/lib-python/2.7/SocketServer.py", line 688, in setup
    self.rfile = self.connection.makefile('rb', self.rbufsize)
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.2.1/site-packages/werkzeug/serving.py", line 368, in makefile
    return socket._fileobject(self._con, mode, bufsize)
  File "/home/adamj/Development/Tools/Python/Interpreters/pypy/pypy-2.2.x/x86_64-portable/lib-python/2.7/socket.py", line 300, in __init__
    sock._reuse()
  File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.2.1/site-packages/OpenSSL/SSL.py", line 838, in __getattr__
    return getattr(self._socket, name)
AttributeError: '_socketobject' object has no attribute '_reuse'
```

A bit more googling and some inspection of the various sources involved (PyPy, PyOpenSSL) let me to lines 292 through 300 of lib-python/2.7/socket.py included with PyPy which reads as follows:

```
#!python
    def __init__(self, sock, mode='rb', bufsize=-1, close=False):
        # Note that a few libraries (like eventlet) poke at the
        # private implementation of socket.py, passing custom
        # objects to _fileobject().  These libraries need the
        # following fix for use on PyPy: the custom objects need
        # methods _reuse() and _drop() that maintains an explicit
        # reference counter, starting at 0.  When it drops back to
        # zero, close() must be called.
        sock._reuse()        
```

Based on the traceback and the comments in the code above it seems that the object being passed in to the _fileobject.__init__ method by Flask is an instance of the class Connection found in PyOpenSSL and that this class does not, in fact, include the necessary methods for PyPy to function correctly.

Can you guys please investigate fixing this issue?

Thanks
Adam

**Comment by hynek** [comment]
Is this still an issue in current versions of pyOpenSSL and PyPy?  If so, please provide an http://sscce.org as jp requested before so we can help you.
