### ISSUE TITLE
X509Extension __str__() method raises exception for unknown extension types

### ISSUE THREAD

**Issue by ich199** [pyca/pyopenssl#1238]
### Issue

When calling the `crypto.X509Extension` method [`__str__()`](https://github.com/pyca/pyopenssl/blob/b259bfbd660f5680783e1abfab27ed0d5bf91c1a/src/OpenSSL/crypto.py#L870), if the extension type is not supported by OpenSSL, an `exception_type` error is raised:

```python
python -c 'from OpenSSL.crypto import X509Extension; print(str(X509Extension(b"1.2.3.4.5.6.7", False, b"DER:05:00")))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/iain/pyopenssl-test/lib64/python3.11/site-packages/OpenSSL/crypto.py", line 882, in __str__
    _openssl_assert(print_result != 0)
  File "/home/iain/pyopenssl-test/lib64/python3.11/site-packages/OpenSSL/_util.py", line 71, in openssl_assert
    exception_from_error_queue(error)
  File "/home/iain/pyopenssl-test/lib64/python3.11/site-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: []
```

### Environment:

```bash
$ python --version
Python 3.11.4

$ pip list
Package      Version
------------ -------
cffi         1.15.1
cryptography 41.0.3
pip          23.2.1
pycparser    2.21
pyOpenSSL    23.2.0
setuptools   62.6.0

$ openssl version
OpenSSL 3.0.9 30 May 2023 (Library: OpenSSL 3.0.9 30 May 2023)
```

### Possible Cause
The current call to [`X509V3_EXT_print()`](https://github.com/pyca/pyopenssl/blob/b259bfbd660f5680783e1abfab27ed0d5bf91c1a/src/OpenSSL/crypto.py#L878C42-L878C42) in `crypto.X509Extension` sets the `flags` parameter (3rd parameter in the call) to `0`, which causes OpenSSL to [return an error](https://github.com/openssl/openssl/blob/master/include/openssl/x509v3.h.in#L489C42-L489C42) for unknown extension types:

```python
print_result = _lib.X509V3_EXT_print(bio, self._extension, 0, 0)
```

### Possible Fix

Update  [`X509V3_EXT_print()`](https://github.com/pyca/pyopenssl/blob/b259bfbd660f5680783e1abfab27ed0d5bf91c1a/src/OpenSSL/crypto.py#L878C42-L878C42) to set the `flags` parameter to one of the other [valid values](https://github.com/openssl/openssl/blob/420a0874db8a6b0070d4820e81e82bf48412d7da/include/openssl/x509v3.h.in#L491-L496) so that it [returns success](https://github.com/openssl/openssl/blob/13342efbb9e16ec8f97b1ac5ab4aa2b3b3490596/crypto/x509/v3_prn.c#L187-L197) for unknown extension types.

eg. amending the call to use the value `1 << 16` or `65536` (`X509V3_EXT_ERROR_UNKNOWN` in OpenSSL) results in the call succeeding and printing `<Not Supported>` for the unknown extension type:

```python
print_result = _lib.X509V3_EXT_print(bio, self._extension, 1 << 16, 0)
```

```
python -c 'from OpenSSL.crypto import X509Extension; print(str(X509Extension(b"1.2.3.4.5.6.7", False, b"DER:05:00")))'
<Not Supported>
```

**Comment by ich199** [comment]
Possibly related to https://github.com/pyca/pyopenssl/issues/270

**Comment by alex** [comment]
`X509Extension` is deprecated and wll be removed.
