### ISSUE TITLE
pyOpenSSL in portable-pypy doesn't cope with NULL errors from RSA certs or multi-level bundles?

### ISSUE THREAD

**Issue by posita** [pyca/pyopenssl#135]
This is adapted from squeaky-pl/portable-pypy#2 as is possibly related to #3. The following is on Debian 7.4 with [pypy-2.3.1-linux_x86_64-portable.tar.bz2](https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-2.3.1-linux_x86_64-portable.tar.bz2) installed into `/opt/site/...` via `virtualenv-pypy /opt/site` from that archive (complete output [here](https://gist.github.com/posita/32fe8738fc3ca79b3d79#file-output_buggy-log)):

```python
	  ...
	  File "/opt/site/site-packages/twisted/protocols/tls.py", line 360, in _flushReceiveBIO
	    bytes = self._tlsConnection.recv(2 ** 15)
	  File "/opt/site/site-packages/OpenSSL/SSL.py", line 995, in recv
	    self._raise_ssl_error(self._ssl, result)
	  File "/opt/site/site-packages/OpenSSL/SSL.py", line 871, in _raise_ssl_error
	    _raise_current_error()
	  File "/opt/site/libexec/pypy-2.3.1-linux_x86_64-portable/lib_pypy/_functools.py", line 22, in __call__
	    return self.func(*(self.args + fargs), **fkeywords)
	  File "/opt/site/site-packages/OpenSSL/_util.py", line 19, in exception_from_error_queue
	    text(lib.ERR_func_error_string(error)),
	  File "/opt/site/site-packages/OpenSSL/_util.py", line 10, in text
	    return native(ffi.string(charp))
	  File "/opt/site/libexec/pypy-2.3.1-linux_x86_64-portable/lib_pypy/cffi/api.py", line 253, in string
	    return self._backend.string(cdata, maxlen)
	exceptions.RuntimeError: cannot use string() on <cdata 'char *' NULL>
```

All files used to reproduce (and complete results) are in [this Gist](https://gist.github.com/posita/32fe8738fc3ca79b3d79):

* [site.key](https://gist.github.com/posita/32fe8738fc3ca79b3d79#file-site-key)
* [site.crt](https://gist.github.com/posita/32fe8738fc3ca79b3d79#file-site-crt)
* [site.ca-bundle](https://gist.github.com/posita/32fe8738fc3ca79b3d79#file-site-ca-bundle)
* [testtwistedssl.py](https://gist.github.com/posita/32fe8738fc3ca79b3d79#file-testtwistedssl-py)

To install portable pypy, download the above archive, unpack it and do:

```sh
% sudo install -d --mode=755 /opt/site
% sudo .../pypy-2.3.1-linux_x86_64-portable/bin/virtualenv-pypy /opt/site
...
% sudo /opt/site/bin/pip install pyOpenSSL service_identity twisted
...
```

To run, save each of the above files into the same directory, and do (e.g.,):
```sh
% /opt/site/bin/twistd --python ./testtwistedssl.py \
    --nodaemon >test.out 2>&1 &
% curl --verbose --insecure --location 'https://127.0.0.1:9876/'
...
```

I cannot reproduce this on OS X with the latest MacPorts OpenSSL (see [here](https://gist.github.com/posita/32fe8738fc3ca79b3d79#file-output_okay-out)).

**Comment by posita** [comment]
> Give me a couple days to retest with your changes.

Apparently, by "a couple days", I mean more than six months. :disappointed:

@alex, I took your #147 branch and merged it with [the latest master](/pyca/pyopenssl/tree/2174e5913a9307ac846dcd84a57f2a0dc99e12d2) (which includes @sholsapp's #155 fix). I resolving the trivial conflict I mentioned in your pull request as follows:

```py
...
def text(charp):
    """
    Get a native string type representing of the given CFFI ``char*`` object.

    :param charp: A C-style string represented using CFFI.

    :return: :class:`str`
    """
    if not charp:
        return ""
    return native(ffi.string(charp))



def exception_from_error_queue(exception_type):
    """
    Convert an OpenSSL library failure into a Python exception.

    When a call to the native OpenSSL library fails, this is usually signalled
    by the return value, and an error code is stored in an error queue
    associated with the current thread. The err library provides functions to
    obtain these error codes and textual error messages.
    """
    ...
```

I now get the same behavior on the client side for the above-failing cases:

```sh
% curl --verbose --insecure --location 'https://10.117.116.99:9876/'
*   Trying 10.117.116.99...
* Connected to 10.117.116.99 (10.117.116.99) port 9876 (#0)
* successfully set certificate verify locations:
*   CAfile: /Users/matt/.site/share/curl/curl-ca-bundle.crt
  CApath: none
* TLSv1.2, TLS Unknown, Unknown (22):
* TLSv1.2, TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to 10.117.116.99:9876
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to 10.117.116.99:9876
% openssl s_client -showcerts -connect 10.117.116.99:9876
CONNECTED(00000003)
140735245194080:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 348 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
---
```

But I no longer get any stack trace on the server side:

```sh
% /opt/site/bin/twistd --python ./testtwistedssl.py --nodaemon
Linux
3.2.0-4-amd64
#1 SMP Debian 3.2.63-2
x86_64
2.7.6 (32f35069a16d819b58c1b6efb17c44e3e53397b2, Jun 10 2014, 00:42:27)
[PyPy 2.3.1 with GCC 4.8.2]
OpenSSL version: 1000105f
pyOpenSSL version: 0.14
/opt/site/site-packages/OpenSSL/__init__.pyc
ssl:9876:privateKey=/vagrant/deploy/files/gist32fe8738fc3ca79b3d79-eeda489dc4855c389ec27b157bbcef8755a48a00/site-self_signed.key:certKey=/vagrant/deploy/files/gist32fe8738fc3ca79b3d79-eeda489dc4855c389ec27b157bbcef8755a48a00/site-self_signed.crt
2015-04-08 11:16:12-0700 [-] Log opened.
2015-04-08 11:16:12-0700 [-] twistd 15.0.0 (/opt/site/bin/pypy 2.7.6) starting up.
2015-04-08 11:16:12-0700 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2015-04-08 11:16:12-0700 [-] Site (TLS) starting on 9876
2015-04-08 11:16:12-0700 [-] Starting factory <twisted.web.server.Site instance at 0x0000000006cbf600>
```

So your fix did a good job of hiding the error, but it looks like there's still an issue?

**Comment by posita** [comment]
For fun, I tried [pypy-2.5.1-linux_x86_64-portable](https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-2.5.1-linux_x86_64-portable.tar.bz2) (which was released after I originally filed this issue), both with and without merging #147. It looks like a linking problem beyond the scope of this issue:

```sh
% rm -fr /opt/site/*
% .../pypy-2.5.1-linux_x86_64-portable/bin/virtualenv-pypy /opt/site
...
% /opt/site/bin/pip install pyOpenSSL service_identity twisted
...
% /opt/site/bin/twistd --python ./testtwistedssl.py --nodaemon
Unhandled Error
Traceback (most recent call last):
  File "/opt/site/site-packages/twisted/application/app.py", line 645, in run
    runApp(config)
  File "/opt/site/site-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/opt/site/site-packages/twisted/application/app.py", line 379, in run
    self.application = self.createOrGetApplication()
  File "/opt/site/site-packages/twisted/application/app.py", line 444, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/opt/site/site-packages/twisted/application/app.py", line 455, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/opt/site/site-packages/twisted/application/service.py", line 403, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/opt/site/site-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "./testtwistedssl.py", line 1, in <module>
    import OpenSSL.SSL
  File "/opt/site/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/site/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/opt/site/site-packages/OpenSSL/_util.py", line 4, in <module>
    binding = Binding()
  File "/opt/site/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 113, in __init__
    self._ensure_ffi_initialized()
  File "/opt/site/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 123, in _ensure_ffi_initialized
    cls._modules,
  File "/opt/site/site-packages/cryptography/hazmat/bindings/utils.py", line 31, in load_library_for_binding
    lib = ffi.verifier.load_library()
  File "/vagrant/deploy/files/pypy-2.5.1-linux_x86_64-portable/lib_pypy/cffi/verifier.py", line 97, in load_library
    return self._load_library()
  File "/vagrant/deploy/files/pypy-2.5.1-linux_x86_64-portable/lib_pypy/cffi/verifier.py", line 207, in _load_library
    return self._vengine.load_library()
  File "/vagrant/deploy/files/pypy-2.5.1-linux_x86_64-portable/lib_pypy/cffi/vengine_gen.py", line 66, in load_library
    module = backend.load_library(filename, flags)
exceptions.OSError: Cannot load library /opt/site/site-packages/cryptography/_Cryptography_cffi_f3e4673fx399b1113.pypy-25.so: /opt/site/site-packages/cryptography/_Cryptography_cffi_f3e4673fx399b1113.pypy-25.so: symbol EC_GFp_nistp521_method, version OPENSSL_1.0.1 not defined in file libcrypto.so.1.0.0 with link time reference

Failed to load application: Cannot load library /opt/site/site-packages/cryptography/_Cryptography_cffi_f3e4673fx399b1113.pypy-25.so: /opt/site/site-packages/cryptography/_Cryptography_cffi_f3e4673fx399b1113.pypy-25.so: symbol EC_GFp_nistp521_method, version OPENSSL_1.0.1 not defined in file libcrypto.so.1.0.0 with link time reference
```

**Comment by posita** [comment]
I also tried an albeit older, but locally installed version of `pypy`:

```sh
% rm -fr /opt/site/*
% which pypy
/usr/bin/pypy
% pypy --version
Python 2.7.3 (2.2.1+dfsg-1, May 16 2014, 17:33:31)
[PyPy 2.2.1 with GCC 4.7.2]
% virtualenv --python=$( which pypy ) /opt/site
...
% /opt/site/bin/pip install pyOpenSSL service_identity twisted
...
```

That version works for all keys/certs. Server output:

```sh
% /opt/site/bin/twistd --python ./testtwistedssl.py --nodaemon
Linux
3.2.0-4-amd64
#1 SMP Debian 3.2.63-2
x86_64
2.7.3 (2.2.1+dfsg-1, May 16 2014, 17:33:31)
[PyPy 2.2.1 with GCC 4.7.2]
OpenSSL version: 1000105f
pyOpenSSL version: 0.14
/opt/site/site-packages/OpenSSL/__init__.py
ssl:9876:privateKey=/vagrant/deploy/files/gist32fe8738fc3ca79b3d79-eeda489dc4855c389ec27b157bbcef8755a48a00/site-self_signed.key:certKey=/vagrant/deploy/files/gist32fe8738fc3ca79b3d79-eeda489dc4855c389ec27b157bbcef8755a48a00/site-self_signed.crt
2015-04-08 12:18:37-0700 [-] Log opened.
2015-04-08 12:18:37-0700 [-] twistd 15.0.0 (/opt/site/bin/pypy 2.7.3) starting up.
2015-04-08 12:18:37-0700 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2015-04-08 12:18:37-0700 [-] Site (TLS) starting on 9876
2015-04-08 12:18:37-0700 [-] Starting factory <twisted.web.server.Site instance at 0x0000000006728760>
2015-04-08 12:19:51-0700 [HTTPChannel (TLSMemoryBIOProtocol),2,10.117.116.1] "10.117.116.1" - - [08/Apr/2015:19:19:51 +0000] "GET / HTTP/1.1" 200 28 "-" "curl/7.41.0"
^C2015-04-08 12:20:45-0700 [-] Received SIGINT, shutting down.
2015-04-08 12:20:45-0700 [-] (TLS Port 9876 Closed)
2015-04-08 12:20:45-0700 [-] Stopping factory <twisted.web.server.Site instance at 0x0000000006728760>
2015-04-08 12:20:45-0700 [-] Main loop terminated.
2015-04-08 12:20:45-0700 [-] Server Shut Down.
```

Client output:

```sh
% curl --verbose --insecure --location https://10.117.116.99:9876/
*   Trying 10.117.116.99...
* Connected to 10.117.116.99 (10.117.116.99) port 9876 (#0)
* successfully set certificate verify locations:
*   CAfile: /Users/matt/.site/share/curl/curl-ca-bundle.crt
  CApath: none
* TLSv1.2, TLS Unknown, Unknown (22):
* TLSv1.2, TLS handshake, Client hello (1):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Server hello (2):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, CERT (11):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Server key exchange (12):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Server finished (14):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Client key exchange (16):
* SSLv2, Unknown (20):
* TLSv1.2, TLS change cipher, Client hello (1):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Finished (20):
* SSLv2, Unknown (20):
* TLSv1.2, TLS change cipher, Client hello (1):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
*        subject: C=US; ST=Desperation; L=Voodoo; O=Gonna Sacrifice Some Chickens at this Point LLC; CN=*.crossyourfingersandgrityourteeth.com
*        start date: 2014-06-25 23:25:53 GMT
*        expire date: 2015-06-25 23:25:53 GMT
*        issuer: C=US; ST=Desperation; L=Voodoo; O=Gonna Sacrifice Some Chickens at this Point LLC; CN=*.crossyourfingersandgrityourteeth.com
*        SSL certificate verify result: self signed certificate (18), continuing anyway.
* SSLv2, Unknown (23):
> GET / HTTP/1.1
> User-Agent: curl/7.41.0
> Host: 10.117.116.99:9876
> Accept: */*
>
* SSLv2, Unknown (23):
< HTTP/1.1 200 OK
< Date: Wed, 08 Apr 2015 19:19:51 GMT
< Content-Length: 28
< Content-Type: text/html
< Server: TwistedWeb/15.0.0
<
* SSLv2, Unknown (23):
<html>Hello, world!</html>
* Connection #0 to host 10.117.116.99 left intact
% openssl s_client -showcerts -connect 10.117.116.99:9876
CONNECTED(00000003)
depth=0 C = US, ST = Desperation, L = Voodoo, O = Gonna Sacrifice Some Chickens at this Point LLC, CN = *.crossyourfingersandgrityourteeth.com
verify error:num=18:self signed certificate
verify return:1
depth=0 C = US, ST = Desperation, L = Voodoo, O = Gonna Sacrifice Some Chickens at this Point LLC, CN = *.crossyourfingersandgrityourteeth.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=Desperation/L=Voodoo/O=Gonna Sacrifice Some Chickens at this Point LLC/CN=*.crossyourfingersandgrityourteeth.com
   i:/C=US/ST=Desperation/L=Voodoo/O=Gonna Sacrifice Some Chickens at this Point LLC/CN=*.crossyourfingersandgrityourteeth.com
-----BEGIN CERTIFICATE-----
MIIDDjCCAnegAwIBAgIJALXbqt5vfS01MA0GCSqGSIb3DQEBBQUAMIGfMQswCQYD
VQQGEwJVUzEUMBIGA1UECAwLRGVzcGVyYXRpb24xDzANBgNVBAcMBlZvb2RvbzE4
MDYGA1UECgwvR29ubmEgU2FjcmlmaWNlIFNvbWUgQ2hpY2tlbnMgYXQgdGhpcyBQ
b2ludCBMTEMxLzAtBgNVBAMMJiouY3Jvc3N5b3VyZmluZ2Vyc2FuZGdyaXR5b3Vy
dGVldGguY29tMB4XDTE0MDYyNTIzMjU1M1oXDTE1MDYyNTIzMjU1M1owgZ8xCzAJ
BgNVBAYTAlVTMRQwEgYDVQQIDAtEZXNwZXJhdGlvbjEPMA0GA1UEBwwGVm9vZG9v
MTgwNgYDVQQKDC9Hb25uYSBTYWNyaWZpY2UgU29tZSBDaGlja2VucyBhdCB0aGlz
IFBvaW50IExMQzEvMC0GA1UEAwwmKi5jcm9zc3lvdXJmaW5nZXJzYW5kZ3JpdHlv
dXJ0ZWV0aC5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBALbD6AZEKoHX
Df23RcyO6zXr7cNUkiFoOvTCRIEGvF9R+uFpVhe7q96yZL1DOYEFkgaRpsUx2X8J
J3Jb4RimIMu3QI4kNo08X0ENX/hZZgx+70OvAJ1lzRKjcDcfqXqRnT1ZjE3Kf7Of
BRiaVtC+nKWIVC+wmrGpUmGwpN92lLiJAgMBAAGjUDBOMB0GA1UdDgQWBBQiA9pt
M9xqfzHkj5bJbb29ruTcVzAfBgNVHSMEGDAWgBQiA9ptM9xqfzHkj5bJbb29ruTc
VzAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4GBABxpuVjWO2XKLM/CkMWR
fJZqb5YmR9i+4PM9otYD196DA0QRM+xsqCLfAib12H9oREvCDlx8S1MrsaQXYfda
PVnugE1JdGnhxDC2ZjyDykInE6adQUMHYfdAqYc+P84T4dhRslBaolyx8mJa/pBN
ltz14v06ksl+S9b5Q6fEmHQI
-----END CERTIFICATE-----
---
Server certificate
subject=/C=US/ST=Desperation/L=Voodoo/O=Gonna Sacrifice Some Chickens at this Point LLC/CN=*.crossyourfingersandgrityourteeth.com
issuer=/C=US/ST=Desperation/L=Voodoo/O=Gonna Sacrifice Some Chickens at this Point LLC/CN=*.crossyourfingersandgrityourteeth.com
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1170 bytes and written 474 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 1024 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: D9523ED2024CDCF254B19E43863D132BA60211F61C1608C67F428511336E69D8
    Session-ID-ctx:
    Master-Key: B1EF7F02F300F0A4BC56E7004CEED3043CEAF26343C7325AE7EB0B720245E7D78320270A59845243C989065DCB4FE9E8
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1428520792
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---
DONE
```

**Comment by posita** [comment]
Still works for all keys/certs with my MacPorts `pypy` as well. Server output:

```sh
% pypy --version
Python 2.7.9 (9c4588d731b7fe0b08669bd732c2b676cb0a8233, Apr 02 2015, 15:24:16)
[PyPy 2.5.1 with GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
% pypy $( which twistd ) --python ./testtwistedssl.py --nodaemon
Darwin
13.4.0
Darwin Kernel Version 13.4.0: Wed Dec 17 19:05:52 PST 2014; root:xnu-2422.115.10~1/RELEASE_X86_64
x86_64
2.7.9 (9c4588d731b7fe0b08669bd732c2b676cb0a8233, Apr 02 2015, 15:24:16)
[PyPy 2.5.1 with GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
OpenSSL version: 9081af
pyOpenSSL version: 0.14
/Users/matt/.virtualenvs/ve-server-pypy/site-packages/pyOpenSSL-0.14-py2.7.egg/OpenSSL/__init__.pyc
ssl:9876:privateKey=/Users/matt/Documents/dev/veritaseum/server/deploy/files/gist32fe8738fc3ca79b3d79-eeda489dc4855c389ec27b157bbcef8755a48a00/site.key:certKey=/Users/matt/Documents/dev/veritaseum/server/deploy/files/gist32fe8738fc3ca79b3d79-eeda489dc4855c389ec27b157bbcef8755a48a00/site.crt:extraCertChain=/Users/matt/Documents/dev/veritaseum/server/deploy/files/gist32fe8738fc3ca79b3d79-eeda489dc4855c389ec27b157bbcef8755a48a00/site.ca-bundle
2015-04-08 12:29:18-0700 [-] Log opened.
2015-04-08 12:29:18-0700 [-] twistd 15.0.0 (/Users/matt/.virtualenvs/ve-server-pypy/bin/pypy 2.7.9) starting up.
2015-04-08 12:29:18-0700 [-] reactor class: twisted.internet.selectreactor.SelectReactor.
2015-04-08 12:29:18-0700 [-] Site (TLS) starting on 9876
2015-04-08 12:29:18-0700 [-] Starting factory <twisted.web.server.Site instance at 0x00000001079834a0>
2015-04-08 12:29:24-0700 [HTTPChannel (TLSMemoryBIOProtocol),0,10.117.116.99] "10.117.116.99" - - [08/Apr/2015:19:29:23 +0000] "GET / HTTP/1.1" 200 28 "-" "curl/7.26.0"
^C2015-04-08 12:29:27-0700 [-] Received SIGINT, shutting down.
2015-04-08 12:29:27-0700 [-] (TLS Port 9876 Closed)
2015-04-08 12:29:27-0700 [-] Stopping factory <twisted.web.server.Site instance at 0x00000001079834a0>
2015-04-08 12:29:27-0700 [-] Main loop terminated.
2015-04-08 12:29:27-0700 [-] Server Shut Down.
```

Client output:

```sh
% curl --verbose --insecure --location https://10.117.116.1:9876/
* About to connect() to 10.117.116.1 port 9876 (#0)
*   Trying 10.117.116.1...
* connected
* Connected to 10.117.116.1 (10.117.116.1) port 9876 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using AES256-SHA
* Server certificate:
*        subject: C=US; ST=Hope; L=Fingers Crossing; O=Value-Add Widgets Co; CN=*.valueaddwidgits.com
*        start date: 2014-06-25 18:21:51 GMT
*        expire date: 2015-06-25 18:21:51 GMT
*        issuer: C=US; ST=Despair; L=Mopetown; O=Super Widgits!, a Division of Internet Widgits Pty Ltd; CN=superwidgits.com
*        SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET / HTTP/1.1
> User-Agent: curl/7.26.0
> Host: 10.117.116.1:9876
> Accept: */*
>
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Server: TwistedWeb/15.0.0
< Date: Wed, 08 Apr 2015 19:30:25 GMT
< Content-Length: 28
< Content-Type: text/html
<
<html>Hello, world!</html>
* Connection #0 to host 10.117.116.1 left intact
* Closing connection #0
* SSLv3, TLS alert, Client hello (1):
% openssl s_client -showcerts -connect 10.117.116.1:9876
CONNECTED(00000003)
depth=1 C = US, ST = Despair, L = Mopetown, O = "Super Widgits!, a Division of Internet Widgits Pty Ltd", CN = superwidgits.com
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/C=US/ST=Hope/L=Fingers Crossing/O=Value-Add Widgets Co/CN=*.valueaddwidgits.com
   i:/C=US/ST=Despair/L=Mopetown/O=Super Widgits!, a Division of Internet Widgits Pty Ltd/CN=superwidgits.com
-----BEGIN CERTIFICATE-----
MIICdDCCAd0CAQEwDQYJKoZIhvcNAQEFBQAwgY4xCzAJBgNVBAYTAlVTMRAwDgYD
VQQIDAdEZXNwYWlyMREwDwYDVQQHDAhNb3BldG93bjE/MD0GA1UECgw2U3VwZXIg
V2lkZ2l0cyEsIGEgRGl2aXNpb24gb2YgSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRk
MRkwFwYDVQQDDBBzdXBlcndpZGdpdHMuY29tMB4XDTE0MDYyNTE4MjE1MVoXDTE1
MDYyNTE4MjE1MVowdjELMAkGA1UEBhMCVVMxDTALBgNVBAgMBEhvcGUxGTAXBgNV
BAcMEEZpbmdlcnMgQ3Jvc3NpbmcxHTAbBgNVBAoMFFZhbHVlLUFkZCBXaWRnZXRz
IENvMR4wHAYDVQQDDBUqLnZhbHVlYWRkd2lkZ2l0cy5jb20wgZ8wDQYJKoZIhvcN
AQEBBQADgY0AMIGJAoGBALQQBY1oI5cfZBajA8iSH1UQvWzNtJ2PC3whZZKj1ODt
chEt4oG3T4DR3j3Mdeu281trCwa9Sbfs2E5ZHst5EHxny7KkJl4As8Gi2ggVtYhZ
tUjmP/N+RFZycx89FSkHCz/c2HBdSydC58xtIqTrJASktVub0dn7xgYCLqVcGwuL
AgMBAAEwDQYJKoZIhvcNAQEFBQADgYEAJIenotC8iKM0BP/lQuYeCFY5YxYgE4tS
T9qlxY2HwFAyxx50nOgJn6uwNOA8XF9XT91ezfsBddZ35rijf29YnmXkU2Auc21d
euoFdQJQkAD+dfM/yfXdLZpW3ItsOLS6hKvvJPqr8tMLZu0l/M9Qp6OXk4xV31bJ
9GsgPipdBaA=
-----END CERTIFICATE-----
 1 s:/C=US/ST=Despair/L=Mopetown/O=Super Widgits!, a Division of Internet Widgits Pty Ltd/CN=superwidgits.com
   i:/C=US/ST=Despair/L=Mopetown/O=Internet Widgits Pty Ltd/CN=widgits.dom
-----BEGIN CERTIFICATE-----
MIICaTCCAdICAQEwDQYJKoZIhvcNAQEFBQAwazELMAkGA1UEBhMCVVMxEDAOBgNV
BAgMB0Rlc3BhaXIxETAPBgNVBAcMCE1vcGV0b3duMSEwHwYDVQQKDBhJbnRlcm5l
dCBXaWRnaXRzIFB0eSBMdGQxFDASBgNVBAMMC3dpZGdpdHMuZG9tMB4XDTE0MDYy
NTE4MTcyNFoXDTE1MDYyNTE4MTcyNFowgY4xCzAJBgNVBAYTAlVTMRAwDgYDVQQI
DAdEZXNwYWlyMREwDwYDVQQHDAhNb3BldG93bjE/MD0GA1UECgw2U3VwZXIgV2lk
Z2l0cyEsIGEgRGl2aXNpb24gb2YgSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMRkw
FwYDVQQDDBBzdXBlcndpZGdpdHMuY29tMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCB
iQKBgQCW4juk51LvPl0JxY80vZ6r/rQXQb2OGvFYhB1uAtXf7pNjZY9N9tV3Ms9r
rKNp+8cPRr7x6EY58P/w7ErrHo5YkSqwHfMNTLKu2+7OnjfYgpN9RgU29BsgN5UF
DxWXcexCZhJiQU2Hbbo846eOea0zlP+d/aUW7GSPqZTN15F28QIDAQABMA0GCSqG
SIb3DQEBBQUAA4GBAIQAEe97xttKpfCE/6IRL9HjMNXRweoMG/FtYyHv+0MA4h+W
1wRwwGK6QMZrMQ6gx03aofRZWj9qOTu/O6tixV7lFfdQVQH1FIsBsgbHdkBe4N9E
EVXNo69UdzOK+OtHJ/vAbYJrswi6LM9mdARQSshetw/gwB7AcosZuOOMC8Xn
-----END CERTIFICATE-----
---
Server certificate
subject=/C=US/ST=Hope/L=Fingers Crossing/O=Value-Add Widgets Co/CN=*.valueaddwidgits.com
issuer=/C=US/ST=Despair/L=Mopetown/O=Super Widgits!, a Division of Internet Widgits Pty Ltd/CN=superwidgits.com
---
No client certificate CA names sent
---
SSL handshake has read 1425 bytes and written 496 bytes
---
New, TLSv1/SSLv3, Cipher is AES256-SHA
Server public key is 1024 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : AES256-SHA
    Session-ID: AF87FE139FB64D7CB088D7A56128E5D0D58197FE7D2AB38065827ED305BC72DB
    Session-ID-ctx:
    Master-Key: 4CA5FFD5184466ABEBFD2B2B77CDD463DE759C4E50E5A7AB336E235570BBA53B78D3EB837BD74315434A5C8BEBFD1462
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1428521424
    Timeout   : 300 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
---
DONE
```

**Comment by posita** [comment]
I was able to get [portable-pypy](/squeaky-pl/portable-pypy) v2.5.1 working by [manually upgrading `cryptography`](https://github.com/squeaky-pl/portable-pypy/issues/9). All my keys/certs worked. Given that this symptom is limited to [portable-pypy](/squeaky-pl/portable-pypy) v2.4 and prior (all of which apparently [statically link OpenSSL](https://github.com/squeaky-pl/portable-pypy/issues/9#issuecomment-91066168)), I'm thinking this isn't an issue with `pyOpenSSL` at all, but rather some artifact of that particular configuration/environment.

Closing as invalid.
