### ISSUE TITLE
KeyError in _raise_ssl_error(), errorcode doesn't have key 0

### ISSUE THREAD

**Issue by aapa** [pyca/pyopenssl#163]
```
Unhandled Error
Traceback (most recent call last):
  File "/home/users/some-user/pyfibot/local/lib/python2.7/site-packages/twisted/python/log.py", line 88, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/users/some-user/pyfibot/local/lib/python2.7/site-packages/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/users/some-user/pyfibot/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/users/some-user/pyfibot/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/users/some-user/pyfibot/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/users/some-user/pyfibot/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in doRead
    return self._dataReceived(data)
  File "/home/users/some-user/pyfibot/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 220, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/users/some-user/pyfibot/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 422, in dataReceived
    self._flushReceiveBIO()
  File "/home/users/some-user/pyfibot/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 360, in _flushReceiveBIO
    bytes = self._tlsConnection.recv(2 ** 15)
  File "/home/users/some-user/pyfibot/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/home/users/some-user/pyfibot/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 862, in _raise_ssl_error
    raise SysCallError(errno, errorcode[errno])
exceptions.KeyError: 0
```

I've found a way to reproduce the error (install pyfibot according to https://github.com/lepinkainen/pyfibot/wiki/Installation, connect to SSL enabled network and flood a link to the bot, usually 10 lines or so is enough), and any ideas helping in debugging this problem is appreciated.

**(EDIT: Barked first the wrong tree)**

**Comment by mhils** [comment]
Hi there,

 we got a bug report for mitmproxy which boils down to the same error (https://github.com/mitmproxy/mitmproxy/issues/461). 
Any way how we can help you with that?

Cheers,
Max

**Comment by alex** [comment]
We now check for 0.
