### ISSUE TITLE
TypeError: context must be a Context instance

### ISSUE THREAD

**Issue by martindanielson** [pyca/pyopenssl#197]
Getting this error on Windows, Python 2.7.9. Working on other machines, this is a new environment.

Any idea on how to solve/debug this?
```
Unhandled exception in thread started by <function inner at 0x02EC6130>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 692, in inner
    passthrough_errors, ssl_context).serve_forever()
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 486, in make_se
rver
    passthrough_errors, ssl_context)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 425, in __init_
_
    self.socket = tsafe.Connection(ssl_context, self.socket)
  File "C:\Python27\lib\site-packages\OpenSSL\tsafe.py", line 11, in __init__
    self._ssl_conn = apply(_ssl.Connection, args)
  File "C:\Python27\lib\site-packages\OpenSSL\SSL.py", line 804, in __init__
    raise TypeError("context must be a Context instance")
TypeError: context must be a Context instance
```

**Comment by exarkun** [comment]
Please use the mailing list, pyopenssl-users at python.org, for questions.  Thanks.
