### ISSUE TITLE
install fail when '_Cryptography_cffi_2a871178xb3816a41' extension

### ISSUE THREAD

**Issue by luojing1211** [pyca/pyopenssl#204]
Hi developers,

I was trying to install pyOpenssl, But it failed at '_Cryptography_cffi_2a871178xb3816a41' extension.
The information is described as follows:
```
>>>
building '_Cryptography_cffi_2a871178xb3816a41' extension

gcc -fno-strict-aliasing -I/Users/jingluo/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/jingluo/anaconda/include/python2.7 -c src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_2a871178xb3816a41.c -o build/temp.macosx-10.5-x86_64-2.7/src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_2a871178xb3816a41.o

In file included from /System/Library/Frameworks/Security.framework/Headers/SecDigestTransform.h:28:0,

                 from src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_2a871178xb3816a41.c:236:

/System/Library/Frameworks/Security.framework/Headers/SecTransform.h:579:15: error: expected identifier or '(' before '^' token

 typedef void (^SecMessageBlock)(CFTypeRef message, CFErrorRef error,

               ^

/System/Library/Frameworks/Security.framework/Headers/SecTransform.h:612:8: error: unknown type name 'SecMessageBlock'

        SecMessageBlock deliveryBlock)

        ^

error: command 'gcc' failed with exit status 1

----------------------------------------

Cleaning up...

  Removing temporary dir /private/var/folders/m9/j7ydtpvs6611q68qycz3nyhr0000gn/T/pip_build_jingluo...
Command /Users/jingluo/anaconda/bin/python -c "import setuptools;__file__='/private/var/folders/m9/j7ydtpvs6611q68qycz3nyhr0000gn/T/pip_build_jingluo/cryptography/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/m9/j7ydtpvs6611q68qycz3nyhr0000gn/T/pip-a6BO1U-record/install-record.txt --single-version-externally-managed failed with error code 1 in /private/var/folders/m9/j7ydtpvs6611q68qycz3nyhr0000gn/T/pip_build_jingluo/cryptography

Exception information:
Traceback (most recent call last):
  File "/Users/jingluo/anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/Users/jingluo/anaconda/lib/python2.7/site-packages/pip/commands/install.py", line 241, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/Users/jingluo/anaconda/lib/python2.7/site-packages/pip/req.py", line 1298, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/Users/jingluo/anaconda/lib/python2.7/site-packages/pip/req.py", line 625, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/Users/jingluo/anaconda/lib/python2.7/site-packages/pip/util.py", line 670, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /Users/jingluo/anaconda/bin/python -c "import setuptools;__file__='/private/var/folders/m9/j7ydtpvs6611q68qycz3nyhr0000gn/T/pip_build_jingluo/cryptography/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/m9/j7ydtpvs6611q68qycz3nyhr0000gn/T/pip-a6BO1U-record/install-record.txt --single-version-externally-managed failed with error code 1 in /private/var/folders/m9/j7ydtpvs6611q68qycz3nyhr0000gn/T/pip_build_jingluo/cryptography
>>>
```
Could you tell me what is missing? My openssl version is:

$ openssl version
OpenSSL 1.0.1k 8 Jan 2015

Thank you .

**Comment by reaperhulk** [comment]
What version of OS X are you running?

**Comment by reaperhulk** [comment]
This might also be a gcc related issue (as it appears to be choking on Apple's C block syntax). What happens if you set CC=clang?

**Comment by luojing1211** [comment]
I am running on OSX 10.9.5.

**Comment by dimpase** [comment]
same  error happens on OSX 10.10.3, with gcc 4.9.2.

**Comment by hynek** [comment]
Please open an issue at https://github.com/pyca/cryptography/issues (if there’s not one already).  

Dependency build errors are nothing the pyOpenSSL project can help with.

**Comment by grzegorz-dubicki** [comment]
Following this comment https://github.com/pyca/cryptography/issues/2350#issuecomment-192895732 resolved my issue with cryptography while installing pyopensll.
