### ISSUE TITLE
Segfault when testing against cryptography 0.6.1 and 0.8.1

### ISSUE THREAD

**Issue by cournape** [pyca/pyopenssl#207]
Hi,

I have noticed some segfaults on pyopnssl 0.14 when running the test suite (using python -m unittest discover OpenSSL).

```
test_export_invalid (OpenSSL.test.test_crypto.CRLTests) ... Segmentation fault
```

Platform details:
- OS: linux 64 bits (centos 5.9)
- python 2.7.6 with openssl 1.0.0b 
- gcc 4.1.2

When running under gdb, I see the following, confirming the issue is with cryptography:

```
#0  0x00002aaab0c40632 in ASN1_item_sign () from /home/vagrant/src/buildsystem-git/build/master-env/bin/../lib/libcrypto.so.1.0.0
#1  0x00002aaab0c646a1 in X509_CRL_sign () from /home/vagrant/src/buildsystem-git/build/master-env/bin/../lib/libcrypto.so.1.0.0
#2  0x00002aaab1374e0d in _cffi_f_X509_CRL_sign (self=<value optimized out>, args=<value optimized out>)
    at cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_36a40ff0x2bad1bae.c:41986
#3  0x00002aaaaab8ca27 in call_function (f=0x16bf830, throwflag=<value optimized out>) at Python/ceval.c:4021
#4  PyEval_EvalFrameEx (f=0x16bf830, throwflag=<value optimized out>) at Python/ceval.c:2666
```

Interestingly, if instead I use python 2.7.9, openssl 1.0.0r and cryptography 0.8.1, I get more or less the same stacktrace:

```
#0  0x00002aaab12f1032 in ASN1_item_sign () from /home/vagrant/src/buildsystem-git/build/master-env/bin/../lib/libcrypto.so.1.0.0
#1  0x00002aaab1315521 in X509_CRL_sign () from /home/vagrant/src/buildsystem-git/build/master-env/bin/../lib/libcrypto.so.1.0.0
#2  0x00002aaab2285a0d in _cffi_f_X509_CRL_sign (self=<value optimized out>, args=<value optimized out>)
    at src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:44199
#3  0x00002aaaaab8e139 in call_function (f=0xb67f40, throwflag=<value optimized out>) at Python/ceval.c:4033
#4  PyEval_EvalFrameEx (f=0xb67f40, throwflag=<value optimized out>) at Python/ceval.c:2679
#5  0x00002aaaaab8f32a in PyEval_EvalCodeEx (co=0x2aaab2770a30, globals=<value optimized out>, locals=<value optimized out>, args=0x2, argcount=3, kws=0x2, kwcount=0,
    defs=0x2aaab0d82ad0, defcount=2, closure=0x0) at Python/ceval.c:3265
```

Note that in both cases, the cryptography test suite passed with no errors.

**Comment by reaperhulk** [comment]
The (probable) issue here is that pyopenssl is passing mostly empty objects to some C functions and older versions of OpenSSL crash rather than handling that case.

**Comment by alex** [comment]
This doesn't happen with supported OpenSSL versions.
