### ISSUE TITLE
Tests error in test_rand.py (v0.15)

### ISSUE THREAD

**Issue by sandrotosi** [pyca/pyopenssl#222]
Hello, here's 2  errors with 0.15 and cryptography 0.8.2

```
running OpenSSL/test/test_rand.py for python2.7 ...
...E............E.
======================================================================
ERROR: test_bytes_paths (__main__.RandTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "OpenSSL/test/test_rand.py", line 209, in test_bytes_paths
    path += NON_ASCII.encode(sys.getfilesystemencoding())
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)

======================================================================
ERROR: test_unicode_paths (__main__.RandTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "OpenSSL/test/test_rand.py", line 219, in test_unicode_paths
    self._read_write_test(path)
  File "OpenSSL/test/test_rand.py", line 184, in _read_write_test
    with open(path, "w"):
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 11: ordinal not in range(128)
```

**Comment by reaperhulk** [comment]
We're investigating now, thank you for the report.

**Comment by hynek** [comment]
does this still occur on master?

**Comment by hynek** [comment]
Closing since CNR anymore.  Please reopen if it still happens.
