### ISSUE TITLE
tests error in test_ssl.py (0.15)

### ISSUE THREAD

**Issue by sandrotosi** [pyca/pyopenssl#223]
Hello, there's a lot of errors in test_ssl with 0.15 and crypto 0.8.2:

```
ERROR: test_load_tmp_dh_bytes (__main__.ContextTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "OpenSSL/test/test_ssl.py", line 1399, in test_load_tmp_dh_bytes
    self.mktemp() + NON_ASCII.encode(getfilesystemencoding()),
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)

======================================================================
ERROR: test_load_tmp_dh_unicode (__main__.ContextTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "OpenSSL/test/test_ssl.py", line 1409, in test_load_tmp_dh_unicode
    self.mktemp().decode(getfilesystemencoding()) + NON_ASCII,
  File "OpenSSL/test/test_ssl.py", line 1386, in _load_tmp_dh_test
    with open(dhfilename, "w") as dhfile:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 11: ordinal not in range(128)

======================================================================
ERROR: test_load_verify_bytes_cafile (__main__.ContextTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "OpenSSL/test/test_ssl.py", line 993, in test_load_verify_bytes_cafile
    cafile = self.mktemp() + NON_ASCII.encode(getfilesystemencoding())
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)

======================================================================
ERROR: test_load_verify_directory_bytes_capath (__main__.ContextTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "OpenSSL/test/test_ssl.py", line 1044, in test_load_verify_directory_bytes_capath
    self.mktemp() + NON_ASCII.encode(getfilesystemencoding())
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)

======================================================================
ERROR: test_load_verify_directory_unicode_capath (__main__.ContextTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "OpenSSL/test/test_ssl.py", line 1055, in test_load_verify_directory_unicode_capath
    self.mktemp().decode(getfilesystemencoding()) + NON_ASCII
  File "OpenSSL/test/test_ssl.py", line 1025, in _load_verify_directory_locations_capath
    makedirs(capath)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 11: ordinal not in range(128)

======================================================================
ERROR: test_load_verify_unicode_cafile (__main__.ContextTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "OpenSSL/test/test_ssl.py", line 1004, in test_load_verify_unicode_cafile
    self.mktemp().decode(getfilesystemencoding()) + NON_ASCII
  File "OpenSSL/test/test_ssl.py", line 980, in _load_verify_cafile
    fObj = open(cafile, 'w')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 11: ordinal not in range(128)

======================================================================
ERROR: test_use_certificate_chain_file_bytes (__main__.ContextTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "OpenSSL/test/test_ssl.py", line 1291, in test_use_certificate_chain_file_bytes
    self.mktemp() + NON_ASCII.encode(getfilesystemencoding())
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)

======================================================================
ERROR: test_use_certificate_chain_file_unicode (__main__.ContextTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "OpenSSL/test/test_ssl.py", line 1302, in test_use_certificate_chain_file_unicode
    self.mktemp().decode(getfilesystemencoding()) + NON_ASCII
  File "OpenSSL/test/test_ssl.py", line 1257, in _use_certificate_chain_file_test
    makedirs(certdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 11: ordinal not in range(128)

======================================================================
ERROR: test_use_certificate_file_bytes (__main__.ContextTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "OpenSSL/test/test_ssl.py", line 548, in test_use_certificate_file_bytes
    filename = self.mktemp() + NON_ASCII.encode(getfilesystemencoding())
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)

======================================================================
ERROR: test_use_certificate_file_unicode (__main__.ContextTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "OpenSSL/test/test_ssl.py", line 559, in test_use_certificate_file_unicode
    self._use_certificate_file_test(filename)
  File "OpenSSL/test/test_ssl.py", line 535, in _use_certificate_file_test
    with open(certificate_file, "wb") as pem_file:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 11: ordinal not in range(128)

======================================================================
ERROR: test_use_privatekey_file_bytes (__main__.ContextTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "OpenSSL/test/test_ssl.py", line 439, in test_use_privatekey_file_bytes
    self.mktemp() + NON_ASCII.encode(getfilesystemencoding()),
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)

======================================================================
ERROR: test_use_privatekey_file_unicode (__main__.ContextTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "OpenSSL/test/test_ssl.py", line 451, in test_use_privatekey_file_unicode
    FILETYPE_PEM,
  File "OpenSSL/test/test_ssl.py", line 424, in _use_privatekey_file_test
    with open(pemfile, "wt") as pem:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 11: ordinal not in range(128)

----------------------------------------------------------------------
```

**Comment by reaperhulk** [comment]
This is confirmed. It's only an issue in the tests, but we'll get a fix out for 0.16.

**Comment by hynek** [comment]
Could you verify if this still happens on the master branch?  Pretty sure we’ve fixed this.

**Comment by hynek** [comment]
Closing, please reopen if still there.
