### ISSUE TITLE
Many failures with ZeroReturnError

### ISSUE THREAD

**Issue by mosheco** [pyca/pyopenssl#279]
See the following exception:
```
>>> import requests
/usr/local/lib64/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
  DeprecationWarning
>>> r=requests.get("http://www.edsurge.com/n/2015-06-09-are-your-teachers-ready-for-student-centered-learning-here-s-how-you-can-tell")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.6/site-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.6/site-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.6/site-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.6/site-packages/requests/sessions.py", line 595, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.6/site-packages/requests/sessions.py", line 189, in resolve_redirects
    allow_redirects=False,
  File "/usr/local/lib/python2.6/site-packages/requests/sessions.py", line 606, in send
    r.content
  File "/usr/local/lib/python2.6/site-packages/requests/models.py", line 724, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.6/site-packages/requests/models.py", line 653, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python2.6/site-packages/requests/packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.6/site-packages/requests/packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib64/python2.6/httplib.py", line 548, in read
    s = self.fp.read(amt)
  File "/usr/lib64/python2.6/socket.py", line 383, in read
    data = self._sock.recv(left)
  File "/usr/local/lib/python2.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 183, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/local/lib/python2.6/site-packages/OpenSSL/SSL.py", line 1320, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.6/site-packages/OpenSSL/SSL.py", line 1167, in _raise_ssl_error
    raise ZeroReturnError()
OpenSSL.SSL.ZeroReturnError
>>>
```
This happens when trying to download many pages from various sites.
Now, the interesting thing is that I can edit the source to just ignore that error using the following patch
```
1167c1167,1168
<             raise ZeroReturnError()
---
>             # raise ZeroReturnError()
> 	    pass
```
(The version I am using is 0.15.1)
and then the download succeeds.

Not sure if this is considered a bug or not but the result is that I am prevented from a successful download.

**Comment by hynek** [comment]
This works for me after installing `requests[security]`:

```
Python 2.7.10 (default, Jun  5 2015, 10:57:55)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests
<module 'requests' from '/Users/hynek/.virtualenvs/03592f3a78e04b54/lib/python2.7/site-packages/requests/__init__.pyc'>
>>> import OpenSSL
>>> OpenSSL
<module 'OpenSSL' from '/Users/hynek/.virtualenvs/03592f3a78e04b54/lib/python2.7/site-packages/OpenSSL/__init__.pyc'>
>>> OpenSSL.version.__version__
'0.15.1'
>>> r = requests.get("http://www.edsurge.com/n/2015-06-09-are-your-teachers-ready-for-student-centered-learning-here-s-how-you-can-tell")
>>> r.ok
True
```

Could it be Python 2.6 related?

**Comment by alex** [comment]
What version of OpenSSL?

**Comment by mosheco** [comment]
@hynek  `requests[security]` was install, but now I upgraded it and this indeed solves the issue.
Thanks.

**Comment by hynek** [comment]
Great :)
