### ISSUE TITLE
Python 2.7 SocketServer socket shutdown is incompatible with pyOpenSSL

### ISSUE THREAD

**Issue by sandrotosi** [pyca/pyopenssl#285]
Forwarding https://bugs.launchpad.net/pyopenssl/+bug/900792 as it seems to be missing:

```
pyOpenSSL's Connection object has a shutdown method taking no arguments. Standard sockets have a shutdown method taking one argument.

Prior to Python 2.7, SocketServer didn't try to use shutdown, but starting in 2.7 it does try to use shutdown. This fails because it passes SHUT_WR as an argument.

Traceback (most recent call last):
  File "demo.py", line 48, in <module>
    test()
  File "demo.py", line 44, in test
    httpd.serve_forever()
  File "/home/exarkun/Projects/python/branches/2.7/Lib/SocketServer.py", line 227, in serve_forever
    self._handle_request_noblock()
  File "/home/exarkun/Projects/python/branches/2.7/Lib/SocketServer.py", line 287, in _handle_request_noblock
    self.shutdown_request(request)
  File "/home/exarkun/Projects/python/branches/2.7/Lib/SocketServer.py", line 459, in shutdown_request
    request.shutdown(socket.SHUT_WR)
TypeError: shutdown() takes exactly 0 arguments (1 given)
```

there are lots of replies in LP, you might want to check them out

**Comment by Zetaphor** [comment]
A workaround for this issue is to add the following function to your handler class

`    def shutdown_request(self, request): request.shutdown()`

**Comment by alex** [comment]
At this point we've dropped support for python2, based on the fact that it's listed explicitly in the title, I'm going to close this. If this is still applicable, let us know and we'll reopen.
