### ISSUE TITLE
Installing OpenSSL 0.15 breaks on mac: `Library not loaded: libssl.1.0.0.dylib`

### ISSUE THREAD

**Issue by chriddyp** [pyca/pyopenssl#290]
We just tried installing `requests[security]` on a fresh virtual environment and are facing an import error. 

We've seen this on Mac 10.9.5 and 10.10.2.

Steps to reproduce:

```                                  
~/my_proj_ana  $ virtualenv venv
New python executable in venv/bin/python
Installing setuptools, pip, wheel...done.

~/my_proj_ana  $ virtualenv -p /Users/Chelsea/anaconda/bin/python venv
Already using interpreter /Users/Chelsea/anaconda/bin/python
New python executable in venv/bin/python
Installing setuptools, pip, wheel...done.

~/my_proj_ana  $ source venv/bin/activate
(venv)                                                                        

~/my_proj_ana  $ pip install requests
Collecting requests
  Using cached requests-2.7.0-py2.py3-none-any.whl
Installing collected packages: requests
Successfully installed requests-2.7.0
(venv)                                                                        

~/my_proj_ana  $ pip install 'requests[security]'
Requirement already satisfied (use --upgrade to upgrade): requests[security] in ./venv/lib/python2.7/site-packages
Collecting pyOpenSSL (from requests[security])
  Using cached pyOpenSSL-0.15.1-py2.py3-none-any.whl
Collecting ndg-httpsclient (from requests[security])
Collecting pyasn1 (from requests[security])
Collecting six>=1.5.2 (from pyOpenSSL->requests[security])
  Using cached six-1.9.0-py2.py3-none-any.whl
Collecting cryptography>=0.7 (from pyOpenSSL->requests[security])
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./venv/lib/python2.7/site-packages (from cryptography>=0.7->pyOpenSSL->requests[security])
Collecting enum34 (from cryptography>=0.7->pyOpenSSL->requests[security])
Collecting idna (from cryptography>=0.7->pyOpenSSL->requests[security])
  Using cached idna-2.0-py2.py3-none-any.whl
Collecting ipaddress (from cryptography>=0.7->pyOpenSSL->requests[security])
  Using cached ipaddress-1.0.7-py27-none-any.whl
Collecting cffi>=0.8 (from cryptography>=0.7->pyOpenSSL->requests[security])
Collecting pycparser (from cffi>=0.8->cryptography>=0.7->pyOpenSSL->requests[security])
Installing collected packages: six, enum34, pyasn1, idna, ipaddress, pycparser, cffi, cryptography, pyOpenSSL, ndg-httpsclient
Successfully installed cffi-1.1.2 cryptography-0.9.1 enum34-1.0.4 idna-2.0 ipaddress-1.0.7 ndg-httpsclient-0.4.0 pyOpenSSL-0.15.1 pyasn1-0.1.8 pycparser-2.14 six-1.9.0
(venv)     

~/my_proj_ana  $ python
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 53, in <module>
    import OpenSSL.SSL
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/OpenSSL/_util.py", line 7, in <module>
    binding = Binding()
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 114, in __init__
    self._ensure_ffi_initialized()
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 126, in _ensure_ffi_initialized
    cls._modules,
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/utils.py", line 31, in load_library_for_binding
    lib = ffi.verifier.load_library()
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cffi/verifier.py", line 97, in load_library
    return self._load_library()
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cffi/verifier.py", line 207, in _load_library
    return self._vengine.load_library()
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cffi/vengine_cpy.py", line 155, in load_library
    raise ffiplatform.VerificationError(error)
cffi.ffiplatform.VerificationError: importing '/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_a269d620xd5c405b7.so': dlopen(/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_a269d620xd5c405b7.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_a269d620xd5c405b7.so
  Reason: image not found
>>> import cryptography
>>> import OpenSSL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/OpenSSL/_util.py", line 7, in <module>
    binding = Binding()
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 114, in __init__
    self._ensure_ffi_initialized()
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 126, in _ensure_ffi_initialized
    cls._modules,
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/utils.py", line 31, in load_library_for_binding
    lib = ffi.verifier.load_library()
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cffi/verifier.py", line 97, in load_library
    return self._load_library()
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cffi/verifier.py", line 207, in _load_library
    return self._vengine.load_library()
  File "/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cffi/vengine_cpy.py", line 155, in load_library
    raise ffiplatform.VerificationError(error)
cffi.ffiplatform.VerificationError: importing '/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_a269d620xd5c405b7.so': dlopen(/Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_a269d620xd5c405b7.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Users/Chelsea/my_proj_ana/venv/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_a269d620xd5c405b7.so
  Reason: image not found
```

Any ideas? Thanks for the help!

**Comment by reaperhulk** [comment]
This is an anaconda problem unfortunately. Anaconda attempts to make things "easier" by creating relative links to underlying shared libraries, but this breaks C linking when you use a different version of a library that is also inside Python. There are two solutions:

1) Don't use anaconda. I kinda wish this was the one everyone would choose but I understand that's difficult.
2) You should be able to install `cryptography` (which `pyOpenSSL` depends on) using `conda` (`conda install cryptography`). Then install `pyOpenSSL` and it should work.

**Comment by chriddyp** [comment]
thx @reaperhulk ! that's brutal, especially when pyOpenSSL is a nested dependency for users! When I `pip install upgrade <any-package-that-might-depend-on-request[security]`, I would never think about digging into its dependencies and figuring out which packages I need to `conda` install and which packages I need to `pip` install. Yikes!

Thanks for your feedback and help on this one.

**Comment by reaperhulk** [comment]
Yeah it's very frustrating and there's nothing we can do about it :( The official anaconda solution is to use conda, but as you said, there's no way to know you're going to pull cryptography in as a dependency a priori.

**Comment by rydevera3** [comment]
This is a great solution! I was having the same issue with OpenSSL and this solution worked great!
