### ISSUE TITLE
missing methods on SSL.Connection

### ISSUE THREAD

**Issue by kaos** [pyca/pyopenssl#293]
I'm looking into an issue I have on one machine (which it seems others have run into as well, see pypa/pip#2696).

As I also have a working installation on another machine, I've been able to narrow it down to that the error message is actually right in the above linked to issue, the `set_tlsext_host_name` method seems to be missing.

Here's from my working setup:
```
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import OpenSSL
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:25: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python.
  DeprecationWarning
>>> OpenSSL.SSL.Connection.set_tlsext_host_name
<unbound method Connection.set_tlsext_host_name>
```

And from my system with issues:
```
Python 2.6.6 (r266:84292, Nov 21 2013, 10:50:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import OpenSSL
>>> OpenSSL.SSL.Connection.set_tlsext_host_name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'OpenSSL.SSL.Connection' has no attribute 'set_tlsext_host_name'
```

There are a few more methods that are 'missing'.. comparing the `dir` output from both systems:
```
>>> dir(OpenSSL.SSL.Connection)
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattr__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_get_finished_message', '_handle_bio_errors', '_raise_ssl_error', '_reverse_mapping', 'accept', 'bio_read', 'bio_shutdown', 'bio_write', 'client_random', 'connect', 'connect_ex', 'do_handshake', 'get_alpn_proto_negotiated', 'get_app_data', 'get_cipher_bits', 'get_cipher_list', 'get_cipher_name', 'get_cipher_version', 'get_client_ca_list', 'get_context', 'get_finished', 'get_next_proto_negotiated', 'get_peer_cert_chain', 'get_peer_certificate', 'get_peer_finished', 'get_servername', 'get_session', 'get_shutdown', 'makefile', 'master_key', 'pending', 'read', 'recv', 'recv_into', 'renegotiate', 'renegotiate_pending', 'send', 'sendall', 'server_random', 'set_accept_state', 'set_alpn_protos', 'set_app_data', 'set_connect_state', 'set_context', 'set_session', 'set_shutdown', 'set_tlsext_host_name', 'shutdown', 'sock_shutdown', 'state_string', 'total_renegotiations', 'want_read', 'want_write', 'write']
```
vs.
```
>>> dir(OpenSSL.SSL.Connection)
['__class__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'accept', 'bio_read', 'bio_shutdown', 'bio_write', 'client_random', 'connect', 'connect_ex', 'do_handshake', 'get_app_data', 'get_cipher_list', 'get_client_ca_list', 'get_context', 'get_peer_certificate', 'get_shutdown', 'makefile', 'master_key', 'pending', 'read', 'recv', 'renegotiate', 'renegotiate_pending', 'send', 'sendall', 'server_random', 'set_accept_state', 'set_app_data', 'set_connect_state', 'set_shutdown', 'shutdown', 'sock_shutdown', 'state_string', 'total_renegotiations', 'want_read', 'want_write', 'write']
```

Both systems have pyOpenSSL 0.15.1, and openssl (with devel package) 1.0.1e. Not sure what else is affecting this..

Looking at the source in `/usr/lib/python-2.6/site-packages/OpenSSL/SSL.py` both system have this method defined.

**Comment by kaos** [comment]
Bah. I removed the `SSL.pyc` file, and now it's the missing method is back. How it got into that state, I have no idea..

The main issue remains, though, as I still get the attribute error (on pip 7.1.0):
```
  File "/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 279, in ssl_wrap_socket
    cnx.set_tlsext_host_name(server_hostname)
AttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
```

**Comment by kaos** [comment]
Ah, finally!

The culprit was that there were an older version from yum installed. So `yum remove pyOpenSSL` solved it. Nasty business, having packages installed from more than one source.

**Comment by hynek** [comment]
I’ll just leave https://hynek.me/articles/virtualenv-lives/ here. ;)  Glad you worked it out though.

**Comment by kaos** [comment]
Haha... thanks :)
