### ISSUE TITLE
Import error under pypy

### ISSUE THREAD

**Issue by alisaifee** [pyca/pyopenssl#299]
Using `pypy 2.5.0` when I install pyOpenSSL (using pip, `pyOpenSSL==0.15.1`) and try to import it I get the following error:

```
>>>> import OpenSSL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ali/.pyenv/versions/sifr-pypy/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Users/ali/.pyenv/versions/sifr-pypy/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/Users/ali/.pyenv/versions/sifr-pypy/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/Users/ali/.pyenv/versions/sifr-pypy/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 11, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: No module named cryptography.hazmat.bindings._openssl
```

**Comment by reaperhulk** [comment]
pypy < 2.6.0 is incompatible with cryptography 1.0. You can either upgrade to pypy 2.6 (recommended if possible) or `pip install cryptography==0.9.3` to fix the issue.

**Comment by alisaifee** [comment]
thanks @reaperhulk
