### ISSUE TITLE
Unable to install pyOpenSSL. 

### ISSUE THREAD

**Issue by Aarushi-Ign** [pyca/pyopenssl#373]
I tried updating requests package by doing pip install requests[security]  --upgrade but my computer got shut down in the middle. I think that happened because what i have next is this whenever i run pip:

Traceback (most recent call last):
  File "C:\Python27\Scripts\pip-script.py", line 9, in <module>
    load_entry_point('pip==7.1.2', 'console_scripts', 'pip')()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2355, in load
    return self.resolve()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python27\lib\site-packages\pip-7.1.2-py2.7.egg\pip\__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Python27\lib\site-packages\pip-7.1.2-py2.7.egg\pip\vcs\mercurial.py", line 10, in <module>
    from pip.download import path_to_url
  File "C:\Python27\lib\site-packages\pip-7.1.2-py2.7.egg\pip\download.py", line 38, in <module>
    from pip._vendor import requests, six
  File "C:\Python27\lib\site-packages\pip-7.1.2-py2.7.egg\pip\_vendor\requests\__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Python27\lib\site-packages\pip-7.1.2-py2.7.egg\pip\_vendor\requests\packages\urllib3\contrib\pyopenssl.py", line 53, in <module>
    import OpenSSL.SSL
  File "build\bdist.win32\egg\OpenSSL\__init__.py", line 8, in <module>
    #
  File "build\bdist.win32\egg\OpenSSL\rand.py", line 11, in <module>
  File "build\bdist.win32\egg\OpenSSL\_util.py", line 6, in <module>
  File "C:\Python27\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
AttributeError: _init_cffi_1_0_external_module

I tried reinstalling pip but then i realized the problem is pyOpenSSL module. It is not properly installed. So pip is not working so i tried easy_install pyOpenSSL.

Searching for pyOpenSSL
Best match: pyOpenSSL 0.15.1
Processing pyopenssl-0.15.1-py2.7.egg
pyopenssl 0.15.1 is already the active version in easy-install.pth

Using c:\python27\lib\site-packages\pyopenssl-0.15.1-py2.7.egg
Processing dependencies for pyOpenSSL
Searching for cffi>=1.1.0
Reading https://pypi.python.org/simple/cffi/
Best match: cffi 1.2.1
Downloading https://pypi.python.org/packages/source/c/cffi/cffi-1.2.1.tar.gz#md5=faca1e420e80433db409bb1bdd0a3f45
Processing cffi-1.2.1.tar.gz
Writing c:\users\aarush~1\appdata\local\temp\easy_install-bs_krb\cffi-1.2.1\setup.cfg
Running cffi-1.2.1\setup.py -q bdist_egg --dist-dir c:\users\aarush~1\appdata\local\temp\easy_install-bs_krb\cffi-1.2.1\egg-dist-tmp-slvddd
error: Setup script exited with error: Microsoft Visual C++ 12.0 is required (Unable to find vcvarsall.bat).
 In that "cffi" module is required.

I download cffi .whl file from http://www.lfd.uci.edu/~gohlke/pythonlibs/ (cffi‑1.2.1‑cp27‑none‑win32.whl) but i can't install it because pip doesn't work. 
and as for working around this error: Microsoft Visual C++ 12.0 is required (Unable to find vcvarsall.bat) is a waste of time because i have tried setting the environmental variables and installing the right Microsoft package. It just doesn't work. Now i am afraid i have to remove python2.7 all together and install again

If anybody have any solution please tell ASAP. Thank you

**Comment by Lukasa** [comment]
@Aarushi-Ign I think the best thing to do here is to reinstall pip. What exact version of Python 2.7 did you install, and when?

**Comment by Aarushi-Ign** [comment]
@Lukasa I did do that. Reinstalled pip but still the pyOpenSSL is different from pip and pip uses pyOpenSSL so pip doesn't work.
and what do u mean by which version of python2.7, the version is 2.7

**Comment by Lukasa** [comment]
@Aarushi-Ign There are sub-versions of Python 2.7, e.g. 2.7.10. Regardless, it's not relevant if you've already reinstalled pip.

To just get pip working again, open up `C:\Python27\lib\site-packages\pip-7.1.2-py2.7.egg\pip_vendor\requests__init_.py` and comment out the block that looks like this:

```python
# Attempt to enable urllib3's SNI support, if possible
try:
    from .packages.urllib3.contrib import pyopenssl
    pyopenssl.inject_into_urllib3()
except ImportError:
    pass
```

(Should be lines 52 to 56). That should get pip working again.

**Comment by Aarushi-Ign** [comment]
@Lukasa Python  version  is 2.7.6 . After i did comment out that block, pip did worked. pip -h works but whenever i try installing a module like pip install pyOpenSSL, this happens:

Traceback (most recent call last):
  File "C:\Python27\Scripts\pip-script.py", line 9, in <module>
    load_entry_point('pip==7.1.2', 'console_scripts', 'pip')()
  File "C:\Python27\lib\site-packages\pip-7.1.2-py2.7.egg\pip\__init__.py", line 217, in main
    return command.main(cmd_args)
  File "C:\Python27\lib\site-packages\pip-7.1.2-py2.7.egg\pip\basecommand.py", line 182, in main
    for name in ["pip._vendor", "distlib", "requests", "urllib3"]
  File "C:\Python27\lib\site-packages\pip-7.1.2-py2.7.egg\pip\compat\dictconfig.py", line 565, in dictConfig
    dictConfigClass(config).configure()
  File "C:\Python27\lib\site-packages\pip-7.1.2-py2.7.egg\pip\compat\dictconfig.py", line 332, in configure
    del logging._handlerList[:]
AttributeError: 'module' object has no attribute '_handlerList'

**Comment by Lukasa** [comment]
That seems like pip is entirely broken: that error is internal to pip. @dstufft, do you have theories here?
