### ISSUE TITLE
FAIL: test_set_verify_callback_exception on FreeBSD (pyopenssl 0.14)

### ISSUE THREAD

**Issue by koobs** [pyca/pyopenssl#38]
OS: FreeBSD 9.2-STABLE #0 r260870
Python: 2.7.6

```
======================================================================
FAIL: test_set_verify_callback_exception (OpenSSL.test.test_ssl.ContextTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/home/user/repos/freebsd/ports/security/py-openssl/work/pyca-pyopenssl-0146d44/OpenSSL/test/test_ssl.py", line 1002, in test_set_verify_callback_exception
    Exception, self._handshake_test, serverContext, clientContext)
  File "/mnt/home/user/repos/freebsd/ports/security/py-openssl/work/pyca-pyopenssl-0146d44/OpenSSL/test/util.py", line 270, in failUnlessRaises
    % (exception.__name__, result))
AssertionError: Exception not raised (None returned)
----------------------------------------------------------------------
```

**Comment by alex** [comment]
This code has also certainly been rewritten in the last 3 years, so I'm going to close. Please comment if this is still an issue.
