### ISSUE TITLE
test_digest FAIL on FreeBSD and Windows (openssl 1.0.1f)

### ISSUE THREAD

**Issue by kouk** [pyca/pyopenssl#41]
```
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/kouk/code/pyopenssl/OpenSSL/test/test_crypto.py", line 1454, in test_digest
    b("A8:EB:07:F8:53:25:0A:F2:56:05:C5:A5:C4:C4:C7:15"))
  File "/usr/local/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
exceptions.AssertionError: 'C1:B5:90:A4:41:11:C8:30:BF:D4:AA:78:13:46:66:59' != 'A8:EB:07:F8:53:25:0A:F2:56:05:C5:A5:C4:C4:C7:15'

OpenSSL.test.test_crypto.X509Tests.test_digest
-------------------------------------------------------------------------------
```

This on `FreeBSD 9.2-RELEASE #0 r255898`, `amd64` with `cryptography` compiled against `OpenSSL 1.0.1f 6 Jan 2014`. Same thing also on Windows 8 64 bit with the same OpenSSL version.

There are other failures as well but they are being addressed in separate issues.

**Comment by alex** [comment]
Pretty sure this is fixed nowadays.
