### ISSUE TITLE
Cannot load private key using crypto.load_privatekey()

### ISSUE THREAD

**Issue by delta24** [pyca/pyopenssl#493]
Hi, I have a MiTM SSL proxy (using Tornado==4.3) and have pyOpenSSL==16 installed.

I get this error when using the `OpenSSL.crypto.load_privatekey()` function:

```
[E 160610 19:56:41 web:1524] Uncaught exception CONNECT ssl.gstatic.com:443 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='ssl.gstatic.com:443', method='CONNECT', uri='ssl.gstatic.com:443', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'ssl.gstatic.com:443', 'Proxy-Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36'})
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/tornado/web.py", line 1401, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/usr/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/viyat/workspace/owtf/framework/http/proxy/proxy.py", line 284, in start_tunnel
        success=ssl_success
      File "/home/viyat/workspace/owtf/framework/http/proxy/socket_wrapper.py", line 24, in wrap_socket
        key, cert = gen_signed_cert(domain, ca_crt, ca_key, ca_pass, certs_folder)
      File "/home/viyat/workspace/owtf/framework/http/proxy/gen_cert.py", line 44, in gen_signed_cert
        ca_key = crypto.load_privatekey(crypto.FILETYPE_PEM, open(ca_key, 'rb').read(), passphrase=ca_pass)
      File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 2483, in load_privatekey
        _raise_current_error()
      File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
        raise exception_type(errors)
    Error: []
[E 160610 19:56:41 web:1946] 500 CONNECT ssl.gstatic.com:443 (127.0.0.1) 140.15ms
```

The `gen_cert` function you see is a function which generates certificates on the fly:

```
#!/usr/bin/env python
'''
# Inbound Proxy Module developed by Bharadwaj Machiraju (blog.tunnelshade.in)
#                     as a part of Google Summer of Code 2013
'''

import os
import hashlib
import re
from OpenSSL import crypto

from framework.lib.filelock import FileLock


def gen_signed_cert(domain, ca_crt, ca_key, ca_pass, certs_folder):
    """
    This function takes a domain name as a parameter and then creates a certificate and key with the
    domain name(replacing dots by underscores), finally signing the certificate using specified CA and
    returns the path of key and cert files. If you are yet to generate a CA then check the top comments
    """
    key_path = os.path.join(certs_folder, re.sub('[^-0-9a-zA-Z_]', '_', domain) + ".key")
    cert_path = os.path.join(certs_folder, re.sub('[^-0-9a-zA-Z_]', '_', domain) + ".crt")

    # The first conditions checks if file exists, and does nothing if true
    # If file doenst exist lock is obtained for writing (Other processes in race must wait)
    # After obtaining lock another check to handle race conditions gracefully
    if os.path.exists(key_path) and os.path.exists(cert_path):
        pass
    else:
        with FileLock(cert_path, timeout=2):
            # Check happens if the certificate and key pair already exists for a domain
            if os.path.exists(key_path) and os.path.exists(cert_path):
                pass
            else:
                # Serial Generation - Serial number must be unique for each certificate,
                # so serial is generated based on domain name
                md5_hash = hashlib.md5()
                md5_hash.update(domain)
                serial = int(md5_hash.hexdigest(), 36)

                # The CA stuff is loaded from the same folder as this script
                ca_cert = crypto.load_certificate(crypto.FILETYPE_PEM, open(ca_crt, 'rb').read())
                # The last parameter is the password for your CA key file
                ca_key = crypto.load_privatekey(crypto.FILETYPE_PEM, open(ca_key, 'rb').read(), passphrase=ca_pass)

                key = crypto.PKey()
                key.generate_key(crypto.TYPE_RSA, 2048)

                cert = crypto.X509()
                cert.get_subject().C = "IN"
                cert.get_subject().ST = "AP"
                cert.get_subject().L = "127.0.0.1"
                cert.get_subject().O = "OWTF"
                cert.get_subject().OU = "Inbound-Proxy"
                cert.get_subject().CN = domain
                cert.gmtime_adj_notBefore(0)
                cert.gmtime_adj_notAfter(365 * 24 * 60 * 60)
                cert.set_serial_number(serial)
                cert.set_issuer(ca_cert.get_subject())
                cert.set_pubkey(key)
                cert.sign(ca_key, "sha1")

                # The key and cert files are dumped and their paths are returned
                domain_key = open(key_path, "w")
                domain_key.write(crypto.dump_privatekey(crypto.FILETYPE_PEM, key))

                domain_cert = open(cert_path, "w")
                domain_cert.write(crypto.dump_certificate(crypto.FILETYPE_PEM, cert))
    return key_path, cert_path
```

and is called with `gen_signed_cert(domain, ca_crt, ca_key, ca_pass, certs_folder)`

I don't understand this error: the function is loading the correct `ca_pass` and everything else works.

**Comment by Lukasa** [comment]
That's definitely a stunningly unhelpful error.

Just to be sure: you're 100% confident that the passphrase is correct *and* that the file pointed to by the `open` command is a valid PEM-encoded private key?

**Comment by reaperhulk** [comment]
An empty error like that typically means it failed to deserialize the key but OpenSSL gave no specific reason. As @Lukasa said could you confirm that you're loading the files you expect?

**Comment by delta24** [comment]
The files are being loaded as intended. But the `ca_pass` being used was an old one (from a fallback address).
Thank you for all the help! :)
