### ISSUE TITLE
Make pyopenssl not relying on having SSLv3 compiled in OpenSSL

### ISSUE THREAD

**Issue by cimnine** [pyca/pyopenssl#550]
On FreeBSD, I configured my OpenSSL to not contain SSLv3 anymore, as it's (IMO) deprecated.

But pyopenssl somehow requires SSLv3 baked into OpenSSL to work, else I get the following traceback when I `import OpenSSL`:

  $ python2
  Python 2.7.12 (default, Sep 27 2016, 01:49:05)
  [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)] on freebsd10
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import OpenSSL
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
      from OpenSSL import rand, crypto, SSL
    File "/usr/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
      from OpenSSL._util import (
    File "/usr/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
      from cryptography.hazmat.bindings.openssl.binding import Binding
    File "/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
      from cryptography.hazmat.bindings._openssl import ffi, lib
  ImportError: /usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: Undefined symbol "SSLv3_server_method"
  >>>

Please make pyopenssl work without relying on old SSLv3 code of OpenSSL.

**Comment by alex** [comment]
Make sure that a) You're running a somewhat-recent cryptography, b) You're linking cryptography against the same version/flags of OpenSSL as you compiled it against.

**Comment by cimnine** [comment]
That's why it failed, thanks!
