### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Cryptography_HAS_SSL_ST'`

### ISSUE THREAD

**Issue by john-bixly** [pyca/pyopenssl#571]
It raises this error. 

`Traceback (most recent call last):
  File "/Users/username/.virtualenvs/env/bin/pip", line 7, in <module>
    from pip import main
  File "/Users/username/.virtualenvs/env/lib/python2.7/site-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/Users/username/.virtualenvs/env/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/Users/username/.virtualenvs/env/lib/python2.7/site-packages/pip/download.py", line 39, in <module>
    from pip._vendor import requests, six
  File "/Users/username/.virtualenvs/env/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Users/username/.virtualenvs/env/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "/Users/username/.virtualenvs/env/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Users/username/.virtualenvs/env/lib/python2.7/site-packages/OpenSSL/SSL.py", line 112, in <module>
    if _lib.Cryptography_HAS_SSL_ST:
AttributeError: 'module' object has no attribute 'Cryptography_HAS_SSL_ST'`

after 

`[example.com] out:   Could not find .egg-info directory in install record for cryptography==1.1 (from -r requirements/base.txt (line 3))
[example.com] out:   Found existing installation: requests 2.11.1
[example.com] out:     Uninstalling requests:
[example.com] out:       Successfully uninstalled requests
[example.com] out:   Found existing installation: simple-salesforce 0.72
[example.com] out:     Uninstalling simple-salesforce:
[example.com] out:       Successfully uninstalled simple-salesforce
[example.com] out:   Running setup.py install for simple-salesforce
[example.com] out:
[example.com] out:   Could not find .egg-info directory in install record for simple-salesforce==0.67.0 (from -r requirements/base.txt (line 28))
[example.com] out: Successfully installed cryptography requests simple-salesforce
[example.com] out: Cleaning up...`

I didn't do anything except deploying changes to server. Now, I can't perform any `pip` commands too.

**Comment by Lukasa** [comment]
You should be able to `pip uninstall pyopenssl` and then `pip install -U pyopenssl` to fix this issue.

**Comment by john-bixly** [comment]
The problem is I can't perform any `pip` commands. But creating new virtualenv worked.

**Comment by hynek** [comment]
This problem pops up when pyOpenSSL is upgraded without upgrading cryptography to the minimum version required.  Sadly setuptools doesn’t enforce dependency versions when upgrading and there’s really nothing we can do about it.
