### ISSUE TITLE
test_ssl.py unittests failing (specificially within the TestContext class)

### ISSUE THREAD

**Issue by caronc** [pyca/pyopenssl#607]
There is no doubt this probably just be an issue between my chair and the keyboard :stuck_out_tongue_winking_eye: but I want to run this by you guys anyway.  The unit tests for pyOpenSSL v16.2.0 give me several failures; but only from one test file:
```
nosetests
.............................................writing RSA key
..........................................MAC verified OK
MAC verified OK
.MAC verified OK
MAC verified OK
..MAC verified OK
MAC verified OK
MAC verified OK
MAC verified OK
MAC verified OK
MAC verified OK
MAC verified OK
MAC verified OK
MAC verified OK
................MAC verified OK
MAC verified OK
MAC verified OK
MAC verified OK
MAC verified OK
MAC verified OK
MAC verified OK
MAC verified OK
MAC verified OK
.MAC verified OK
MAC verified OK
...................................................................................................................................................................................................................................................................................................................................................................EEEEEEEE......
======================================================================
ERROR: :meth:`Context.load_client_ca` works as far as we can tell.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_load_client_ca() takes exactly 3 arguments (1 given)

======================================================================
ERROR: :meth:`Context.load_client_ca` raises an Error if the ca file is
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_load_client_ca_invalid() takes exactly 3 arguments (1 given)

======================================================================
ERROR: Passing the path as unicode raises a warning but works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_load_client_ca_unicode() takes exactly 3 arguments (1 given)

======================================================================
ERROR: :meth:`Context.set_cipher_list` accepts both byte and unicode strings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_set_cipher_list() takes exactly 3 arguments (1 given)

======================================================================
ERROR: :meth:`Context.set_cipher_list` raises :exc:`TypeError` when passed a
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_set_cipher_list_wrong_args() takes exactly 4 arguments (1 given)

======================================================================
ERROR: :meth:`Context.set_session_id` works as far as we can tell.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_set_session_id() takes exactly 2 arguments (1 given)

======================================================================
ERROR: :meth:`Context.set_session_id` errors are propagated.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_set_session_id_fail() takes exactly 2 arguments (1 given)

======================================================================
ERROR: :meth:`Context.set_session_id` raises a warning if a unicode string is
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_set_session_id_unicode() takes exactly 2 arguments (1 given)

----------------------------------------------------------------------
Ran 476 tests in 7.541s

FAILED (errors=8)
```
Basically everything in _test_ssl.py_ is failing from within the __TestContext()__ class.
I'm getting this error using cryptography v1.7.2,  pytest v3.0.6, and  six v1.10.0
I'm using Python 2.7.5 (stock CentOS 7.x)

Is there anything I'm missing here?

**Comment by hynek** [comment]
Um Im surprised so many Pass if you use nosetests.  We had plenty pytest-only tests and are 100% pytest-only now.

**Comment by caronc** [comment]
Thanks for your fast response; when i flip it to pytest (as it should have been in the first place) i get an older issue that you closed in the past (#222 & #223):

```
...snip...
tests/test_rand.py::RandTests::test_bytes_paths FAILED
tests/test_rand.py::RandTests::test_unicode_paths FAILED
tests/test_ssl.py::ContextTests::test_load_tmp_dh_bytes FAILED
tests/test_ssl.py::ContextTests::test_load_tmp_dh_unicode FAILED
tests/test_ssl.py::ContextTests::test_load_verify_bytes_cafile FAILED
tests/test_ssl.py::ContextTests::test_load_verify_directory_bytes_capath FAILED
tests/test_ssl.py::ContextTests::test_load_verify_directory_unicode_capath FAILED
tests/test_ssl.py::ContextTests::test_load_verify_unicode_cafile FAILED
tests/test_ssl.py::ContextTests::test_use_certificate_chain_file_bytes FAILED
tests/test_ssl.py::ContextTests::test_use_certificate_chain_file_unicode FAILED
tests/test_ssl.py::ContextTests::test_use_certificate_file_bytes FAILED
tests/test_ssl.py::ContextTests::test_use_certificate_file_unicode FAILED
tests/test_ssl.py::ContextTests::test_use_privatekey_file_bytes FAILED
tests/test_ssl.py::ContextTests::test_use_privatekey_file_unicode FAILED
...snip...
```
Everything else passes fine.

Here is the output of the failures:
```
=================================== FAILURES ===================================
__________________________ RandTests.test_bytes_paths __________________________

self = <tests.test_rand.RandTests testMethod=test_bytes_paths>

    def test_bytes_paths(self):
        """
            Random data can be saved and loaded to files with paths specified as
            bytes.
            """
        path = self.mktemp()
>       path += NON_ASCII.encode(sys.getfilesystemencoding())
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)

tests/test_rand.py:186: UnicodeEncodeError
_________________________ RandTests.test_unicode_paths _________________________

self = <tests.test_rand.RandTests testMethod=test_unicode_paths>

    def test_unicode_paths(self):
        """
            Random data can be saved and loaded to files with paths specified as
            unicode.
            """
        path = self.mktemp().decode('utf-8') + NON_ASCII
>       self._read_write_test(path)

tests/test_rand.py:195: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.test_rand.RandTests testMethod=test_unicode_paths>
path = './tmpdg3sjZ/tmpuFI3yQ\u2603'

    def _read_write_test(self, path):
        """
            Verify that ``rand.write_file`` and ``rand.load_file`` can be used.
            """
        # Create the file so cleanup is more straightforward
>       with open(path, "w"):
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 21: ordinal not in range(128)

tests/test_rand.py:162: UnicodeEncodeError
_____________________ ContextTests.test_load_tmp_dh_bytes ______________________

self = <tests.test_ssl.ContextTests testMethod=test_load_tmp_dh_bytes>

    def test_load_tmp_dh_bytes(self):
        """
            :py:obj:`Context.load_tmp_dh` loads Diffie-Hellman parameters from the
            specified file (given as ``bytes``).
            """
        self._load_tmp_dh_test(
>           self.mktemp() + NON_ASCII.encode(getfilesystemencoding()),
        )
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)

tests/test_ssl.py:1504: UnicodeEncodeError
____________________ ContextTests.test_load_tmp_dh_unicode _____________________

self = <tests.test_ssl.ContextTests testMethod=test_load_tmp_dh_unicode>

    def test_load_tmp_dh_unicode(self):
        """
            :py:obj:`Context.load_tmp_dh` loads Diffie-Hellman parameters from the
            specified file (given as ``unicode``).
            """
        self._load_tmp_dh_test(
>           self.mktemp().decode(getfilesystemencoding()) + NON_ASCII,
        )

tests/test_ssl.py:1513: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.test_ssl.ContextTests testMethod=test_load_tmp_dh_unicode>
dhfilename = './tmpV6E2C8/tmpdCLR_g\u2603'

    def _load_tmp_dh_test(self, dhfilename):
        """
            Verify that calling ``Context.load_tmp_dh`` with the given filename
            does not raise an exception.
            """
        context = Context(TLSv1_METHOD)
>       with open(dhfilename, "w") as dhfile:
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 21: ordinal not in range(128)

tests/test_ssl.py:1492: UnicodeEncodeError
__________________ ContextTests.test_load_verify_bytes_cafile __________________

self = <tests.test_ssl.ContextTests testMethod=test_load_verify_bytes_cafile>

    def test_load_verify_bytes_cafile(self):
        """
            :py:obj:`Context.load_verify_locations` accepts a file name as a
            ``bytes`` instance and uses the certificates within for verification
            purposes.
            """
>       cafile = self.mktemp() + NON_ASCII.encode(getfilesystemencoding())
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)

tests/test_ssl.py:1105: UnicodeEncodeError
_____________ ContextTests.test_load_verify_directory_bytes_capath _____________

self = <tests.test_ssl.ContextTests testMethod=test_load_verify_directory_bytes_capath>

    def test_load_verify_directory_bytes_capath(self):
        """
            :py:obj:`Context.load_verify_locations` accepts a directory name as a
            ``bytes`` instance and uses the certificates within for verification
            purposes.
            """
        self._load_verify_directory_locations_capath(
>           self.mktemp() + NON_ASCII.encode(getfilesystemencoding())
        )
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)

tests/test_ssl.py:1152: UnicodeEncodeError
____________ ContextTests.test_load_verify_directory_unicode_capath ____________

self = <tests.test_ssl.ContextTests testMethod=test_load_verify_directory_unicode_capath>

    def test_load_verify_directory_unicode_capath(self):
        """
            :py:obj:`Context.load_verify_locations` accepts a directory name as a
            ``unicode`` instance and uses the certificates within for verification
            purposes.
            """
        self._load_verify_directory_locations_capath(
>           self.mktemp().decode(getfilesystemencoding()) + NON_ASCII
        )

tests/test_ssl.py:1162: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_ssl.py:1134: in _load_verify_directory_locations_capath
    makedirs(capath)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = './tmpK9MAiQ/tmprTrtLE\u2603', mode = 511

    def makedirs(name, mode=0777):
        """makedirs(path [, mode=0777])
    
        Super-mkdir; create a leaf directory and all intermediate ones.
        Works like mkdir, except that any intermediate path segment (not
        just the rightmost) will be created if it does not exist.  This is
        recursive.
    
        """
        head, tail = path.split(name)
        if not tail:
            head, tail = path.split(head)
        if head and tail and not path.exists(head):
            try:
                makedirs(head, mode)
            except OSError, e:
                # be happy if someone already created the path
                if e.errno != errno.EEXIST:
                    raise
            if tail == curdir:           # xxx/newdir/. exists if xxx/newdir exists
                return
>       mkdir(name, mode)
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 21: ordinal not in range(128)

/usr/lib64/python2.7/os.py:157: UnicodeEncodeError
_________________ ContextTests.test_load_verify_unicode_cafile _________________

self = <tests.test_ssl.ContextTests testMethod=test_load_verify_unicode_cafile>

    def test_load_verify_unicode_cafile(self):
        """
            :py:obj:`Context.load_verify_locations` accepts a file name as a
            ``unicode`` instance and uses the certificates within for verification
            purposes.
            """
        self._load_verify_cafile(
>           self.mktemp().decode(getfilesystemencoding()) + NON_ASCII
        )

tests/test_ssl.py:1115: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.test_ssl.ContextTests testMethod=test_load_verify_unicode_cafile>
cafile = './tmplwhjQ6/tmp_Yfx2x\u2603'

    def _load_verify_cafile(self, cafile):
        """
            Verify that if path to a file containing a certificate is passed to
            ``Context.load_verify_locations`` for the ``cafile`` parameter, that
            certificate is used as a trust root for the purposes of verifying
            connections created using that ``Context``.
            """
>       fObj = open(cafile, 'w')
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 21: ordinal not in range(128)

tests/test_ssl.py:1093: UnicodeEncodeError
______________ ContextTests.test_use_certificate_chain_file_bytes ______________

self = <tests.test_ssl.ContextTests testMethod=test_use_certificate_chain_file_bytes>

    def test_use_certificate_chain_file_bytes(self):
        """
            ``Context.use_certificate_chain_file`` accepts the name of a file (as
            an instance of ``bytes``) to specify additional certificates to use to
            construct and verify a trust chain.
            """
        self._use_certificate_chain_file_test(
>           self.mktemp() + NON_ASCII.encode(getfilesystemencoding())
        )
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)

tests/test_ssl.py:1400: UnicodeEncodeError
_____________ ContextTests.test_use_certificate_chain_file_unicode _____________

self = <tests.test_ssl.ContextTests testMethod=test_use_certificate_chain_file_unicode>

    def test_use_certificate_chain_file_unicode(self):
        """
            ``Context.use_certificate_chain_file`` accepts the name of a file (as
            an instance of ``unicode``) to specify additional certificates to use
            to construct and verify a trust chain.
            """
        self._use_certificate_chain_file_test(
>           self.mktemp().decode(getfilesystemencoding()) + NON_ASCII
        )

tests/test_ssl.py:1410: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_ssl.py:1367: in _use_certificate_chain_file_test
    makedirs(certdir)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = './tmpFV0MNT/tmpyh6kki\u2603', mode = 511

    def makedirs(name, mode=0777):
        """makedirs(path [, mode=0777])
    
        Super-mkdir; create a leaf directory and all intermediate ones.
        Works like mkdir, except that any intermediate path segment (not
        just the rightmost) will be created if it does not exist.  This is
        recursive.
    
        """
        head, tail = path.split(name)
        if not tail:
            head, tail = path.split(head)
        if head and tail and not path.exists(head):
            try:
                makedirs(head, mode)
            except OSError, e:
                # be happy if someone already created the path
                if e.errno != errno.EEXIST:
                    raise
            if tail == curdir:           # xxx/newdir/. exists if xxx/newdir exists
                return
>       mkdir(name, mode)
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 21: ordinal not in range(128)

/usr/lib64/python2.7/os.py:157: UnicodeEncodeError
_________________ ContextTests.test_use_certificate_file_bytes _________________

self = <tests.test_ssl.ContextTests testMethod=test_use_certificate_file_bytes>

    def test_use_certificate_file_bytes(self):
        """
            :py:obj:`Context.use_certificate_file` sets the certificate (given as a
            ``bytes`` filename) which will be used to identify connections created
            using the context.
            """
>       filename = self.mktemp() + NON_ASCII.encode(getfilesystemencoding())
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)

tests/test_ssl.py:683: UnicodeEncodeError
________________ ContextTests.test_use_certificate_file_unicode ________________

self = <tests.test_ssl.ContextTests testMethod=test_use_certificate_file_unicode>

    def test_use_certificate_file_unicode(self):
        """
            :py:obj:`Context.use_certificate_file` sets the certificate (given as a
            ``bytes`` filename) which will be used to identify connections created
            using the context.
            """
        filename = self.mktemp().decode(getfilesystemencoding()) + NON_ASCII
>       self._use_certificate_file_test(filename)

tests/test_ssl.py:693: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.test_ssl.ContextTests testMethod=test_use_certificate_file_unicode>
certificate_file = './tmpJ3ARIG/tmpd1vN61\u2603'

    def _use_certificate_file_test(self, certificate_file):
        """
            Verify that calling ``Context.use_certificate_file`` with the given
            filename doesn't raise an exception.
            """
        # TODO
        # Hard to assert anything.  But we could set a privatekey then ask
        # OpenSSL if the cert and key agree using check_privatekey.  Then as
        # long as check_privatekey works right we're good...
>       with open(certificate_file, "wb") as pem_file:
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 21: ordinal not in range(128)

tests/test_ssl.py:671: UnicodeEncodeError
_________________ ContextTests.test_use_privatekey_file_bytes __________________

self = <tests.test_ssl.ContextTests testMethod=test_use_privatekey_file_bytes>

    def test_use_privatekey_file_bytes(self):
        """
            A private key can be specified from a file by passing a ``bytes``
            instance giving the file name to ``Context.use_privatekey_file``.
            """
        self._use_privatekey_file_test(
>           self.mktemp() + NON_ASCII.encode(getfilesystemencoding()),
            FILETYPE_PEM,
        )
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 0: ordinal not in range(128)

tests/test_ssl.py:576: UnicodeEncodeError
________________ ContextTests.test_use_privatekey_file_unicode _________________

self = <tests.test_ssl.ContextTests testMethod=test_use_privatekey_file_unicode>

    def test_use_privatekey_file_unicode(self):
        """
            A private key can be specified from a file by passing a ``unicode``
            instance giving the file name to ``Context.use_privatekey_file``.
            """
        self._use_privatekey_file_test(
            self.mktemp().decode(getfilesystemencoding()) + NON_ASCII,
>           FILETYPE_PEM,
        )

tests/test_ssl.py:587: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.test_ssl.ContextTests testMethod=test_use_privatekey_file_unicode>
pemfile = './tmpJO5pD0/tmpQfWm1M\u2603', filetype = 1

    def _use_privatekey_file_test(self, pemfile, filetype):
        """
            Verify that calling ``Context.use_privatekey_file`` with the given
            arguments does not raise an exception.
            """
        key = PKey()
        key.generate_key(TYPE_RSA, 128)
    
>       with open(pemfile, "wt") as pem:
E       UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 21: ordinal not in range(128)

tests/test_ssl.py:562: UnicodeEncodeError
==================== 14 failed, 464 passed in 11.65 seconds ====================
```
Any advice would be awesome!

**Comment by hynek** [comment]
I’m sorry but I’m not gonna invest time into why tests fail on “historic” versions of pyOpenSSL.  We’ve put a lot of work into stabilizing them over time (running them when we took the project over was far from trivial) so I’m only interested if the current master is passing?  You may also have more luck by trying to use tox.

**Comment by caronc** [comment]
Your response is understandable.  I should clarify that I am trying to build the latest version (of pyOpenSSL) off of pypi (v16.2.0) and receiving these errors. My goal is to actually update the (legacy) version that ships with _CentOS/RedHat v7.x_ (currently pyOpenSSL v0.13 - scary right...) to a more up to date one.

I would think that the only legacy component in this entire operation would be that I'm using the stock version of python (2.7.5) as all of the required dependencies for this product have been met at this point.

The only other thing worth mentioning at this point might be that I'm using openssl v1.0.1e-51 which is the version shipped and fully supported by RedHat. I presume the current copy of pyOpenSSL is compatible here or could this be a problem?
