### ISSUE TITLE
"unable to get issuer certificate" even though `openssl verify` returns  OK

### ISSUE THREAD

**Issue by anka-sirota** [pyca/pyopenssl#608]
I have a certificate that I'm trying to validate against a Comodo RSA CA, and it works fine with `openssl verify`:

```bash
$ openssl verify -CAfile comodo-rsa.ca test.crt
test.crt: OU = Domain Control Validated, OU = PositiveSSL, CN = www.magento.henkslaaf.nl
error 10 at 0 depth lookup:certificate has expired
OK
```

However when the same certificates are used in `X509StoreContext`, `verify_certificate` fails with "unable to get issuer certificate":

```python
from OpenSSL.crypto import FILETYPE_PEM, load_certificate, X509Store, X509StoreContext


with open("test.crt") as f:
    raw_crt = f.read().rstrip()
with open("comodo-rsa.ca") as f:
    raw_ca = f.read().rstrip()

crt = load_certificate(FILETYPE_PEM, raw_crt)
ca = load_certificate(FILETYPE_PEM, raw_ca)

store = X509Store()
store.add_cert(ca)
store_ctx = X509StoreContext(store, crt)
store_ctx.verify_certificate()
```

```
Traceback (most recent call last):
  File "/tmp/cert_test.py", line 15, in <module>
    store_ctx.verify_certificate()
  File "/media/extra/envs/pino/local/lib/python2.7/site-packages/OpenSSL/crypto.py", line 1634, in verify_certificate
    raise self._exception_from_context()
OpenSSL.crypto.X509StoreContextError: [2, 1, 'unable to get issuer certificate']
```

Same snippet works fine with other pairs of certificates, but not this one
I'm not quite sure how to debug this, so any suggestion about what could cause this difference would be greatly appreciated.

The error seems to point out to an incomplete chain, but the goal is not to verify the whole chain, only to verify that `test.crt` has been issues/signed by `comodo-rsa.ca`, which `openssl verify` does perfectly. Is there a way to match this exact behaviour?

**Comment by anka-sirota** [comment]
my bad, CA that was used did contain a chain, while `add_cert` only loads one cert, which was the root cert and not the CA that issued the `test.crt`, hence the error.

Using `pem` to split the chain fixed the issue:

```python
from OpenSSL.crypto import FILETYPE_PEM, load_certificate, X509Store, X509StoreContext
import pem


with open("test.crt") as f:
    raw_crt = f.read().rstrip()
with open("comodo-rsa.ca") as f:
    raw_ca = f.read().rstrip()

crt = load_certificate(FILETYPE_PEM, raw_crt)
ca = load_certificate(FILETYPE_PEM, raw_ca)

store = X509Store()
for _ca in pem.parse(raw_ca):
    store.add_cert(load_certificate(FILETYPE_PEM, str(_ca)))
store_ctx = X509StoreContext(store, crt)
store_ctx.verify_certificate()
```
