### ISSUE TITLE
Python3 and OpenSSL.crypto.dump_privatekey() error 

### ISSUE THREAD

**Issue by Spredzy** [pyca/pyopenssl#681]
When using Python 3 and `OpenSSL.crypto.dump_privatekey()` and trying to leverage the cipher/passphrase options I stumbled across a type issue.

**Context**: Python 2.7.13 / pyOpenSSL 17.1.0 (same issue with current master)

```
import OpenSSL

if __name__ == "__main__":

    print(OpenSSL.__version__)

    privatekey = OpenSSL.crypto.PKey()
    privatekey.generate_key(OpenSSL.crypto.TYPE_RSA, 4096)

    with open('/tmp/mypkey.pem', 'w') as f:
        f.write(OpenSSL.crypto.dump_privatekey(
            OpenSSL.crypto.FILETYPE_PEM,
            privatekey,
            'aes256',
            'test')
        )
```

**Conclusion**: Works fine

**Context**: Python 3.5.3 / pyOpenSSL 17.2.0 (same issue with current master) / same script as the above

```
Traceback (most recent call last):
  File "pkey.py", line 15, in <module>
    'test')
  File "/usr/lib/python3.5/site-packages/OpenSSL/crypto.py", line 1843, in dump_privatekey
    helper.callback, helper.callback_args)
  File "/usr/lib/python3.5/site-packages/OpenSSL/crypto.py", line 2611, in callback
    "Last argument must be a byte string or a callable."
TypeError: Last argument must be a byte string or a callable.
```

**Context**: Python 3.5.3 / pyOpenSSL 17.2.0 (same issue with current master) 

```
import OpenSSL

if __name__ == "__main__":

    print(OpenSSL.__version__)

    privatekey = OpenSSL.crypto.PKey()
    privatekey.generate_key(OpenSSL.crypto.TYPE_RSA, 4096)

    with open('/tmp/mypkey.pem', 'w') as f:
        f.write(OpenSSL.crypto.dump_privatekey(
            OpenSSL.crypto.FILETYPE_PEM,
            privatekey,
            b'aes256',
            b'test')
        )
```

**Conclusion**: 

```
Traceback (most recent call last):
  File "pkey.py", line 15, in <module>
    b'test')
  File "/usr/lib/python3.5/site-packages/OpenSSL/crypto.py", line 1833, in dump_privatekey
    cipher_obj = _lib.EVP_get_cipherbyname(_byte_string(cipher))
  File "/usr/lib/python3.5/site-packages/OpenSSL/_util.py", line 112, in byte_string
    return s.encode("charmap")
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by alex** [comment]
The password argument `b"test"` must be bytes, but the ciphername `"aes256"` should be a string. I've confirmed that `OpenSSL.crypto.dump_privatekey(OpenSSL.crypto.FILETYPE_PEM, key, 'aes256', b'test')` works on both python2 and 3.
