### ISSUE TITLE
17.5.0: ImportError: cannot import name certificate_transparency

### ISSUE THREAD

**Issue by wlongabaugh** [pyca/pyopenssl#729]
Yesterday, using 17.4.0, this call worked fine:
import urllib3.contrib.pyopenssl

Installed:

urllib3 (1.22)
cryptography (2.1.4)

Today, using 17.5.0, I get the stack trace below:
 
```
Traceback (most recent call last):
  File "*****", line **, in <module>
    import urllib3.contrib.pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency
ImportError: cannot import name certificate_transparency

```

**Comment by alex** [comment]
This means somehow cryptography was not installed correctly. Are you able to give us instructions to reproduce this from a clean environment?

**Comment by wlongabaugh** [comment]
You are correct. Since the version change between yesterday (17.4.0) and today (17.5.0) included changes to files in the stack trace, I jumped to the wrong conclusion. I have resolved the issue through changing my install script. Sorry for the bogus report.
