### ISSUE TITLE
ERROR: test_set_default_verify_paths on NetBSD

### ISSUE THREAD

**Issue by 0-wiz-0** [pyca/pyopenssl#75]
I see a test failure with pyOpenSSL-0.14 and cryptography-0.2.2:

ERROR: test_set_default_verify_paths (OpenSSL.test.test_ssl.ContextTests)

Traceback (most recent call last):
File "/scratch/security/py-OpenSSL/work/pyOpenSSL-0.14/OpenSSL/test/test_ssl.py", line 933, in test_set_default_verify_paths
clientSSL.do_handshake()
File "/scratch/security/py-OpenSSL/work/pyOpenSSL-0.14/OpenSSL/SSL.py", line 1076, in do_handshake
self._raise_ssl_error(self._ssl, result)
File "/scratch/security/py-OpenSSL/work/pyOpenSSL-0.14/OpenSSL/SSL.py", line 871, in _raise_ssl_error
_raise_current_error()
File "/scratch/security/py-OpenSSL/work/pyOpenSSL-0.14/OpenSSL/_util.py", line 22, in exception_from_error_queue
raise exceptionType(errors)
OpenSSL.SSL.Error: [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]

This is in a sandbox with no certificates installed, in case it matters, and openssl-1.0.1f.

**Comment by alex** [comment]
Unless there's a specific alternative here, this is sort of workign as intended.
