### ISSUE TITLE
HTTPServer compatibility

### ISSUE THREAD

**Issue by arn-vollebregt-kpn** [pyca/pyopenssl#846]
I am trying to port a [Python recipe](http://code.activestate.com/recipes/442473-simple-http-server-supporting-ssl-secure-communica/) from *Python2* to *Python3* but I am running into issues ([seemingly](https://stackoverflow.com/questions/1150653/python-2-5-socket-fileobject-is-what-in-python-3-1) because pyopenssl does not support *SocketIO*?). This is the only issue preventing me to migrate my codebase from *Python2* to  *Python3*.

My code is as follows:
```python
### Generate server key material ###
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout serverPrivateKey.pem -out serverCertificate.pem -subj "/C=''/O=''/OU=''/CN=server"
### Generate client key material ###
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout clientPrivateKey.pem -out clientCertificate.pem -subj "/C=''/O=''/OU=''/CN=client"
from __future__ import print_function
import socket, sys, os
try:    # python2 compatible
    from SocketServer import BaseServer
    from BaseHTTPServer import HTTPServer
    from SimpleHTTPServer import SimpleHTTPRequestHandler
except: # python3 compatible
    from socketserver import BaseServer
    from http.server import HTTPServer, SimpleHTTPRequestHandler
from OpenSSL import SSL

def verifyCallback(conn, cert, errno, depth, result):
    print('\'verifyCallback\' called for {0} (conn={1},cert={2},errno={3},depth={4},result={5}'.format(conn._socket.getpeername()[0],conn,cert,errno,depth,result))
    return True

def sniCallback(conn):
    print('\'sniCallback\' called for {0} (conn={1})'.format(conn._socket.getpeername()[0],conn))

class SecureHTTPServer(HTTPServer):
    def __init__(self, server_address, HandlerClass):
        BaseServer.__init__(self, server_address, HandlerClass)
        ctx = SSL.Context(SSL.TLSv1_2_METHOD)
        ctx.use_privatekey_file('serverPrivateKey.pem')
        ctx.use_certificate_file('serverCertificate.pem')
        # https://www.pyopenssl.org/en/stable/api/ssl.html#OpenSSL.SSL.Context.set_verify
        ctx.set_verify(SSL.VERIFY_PEER, verifyCallback)
        # https://pyopenssl.org/en/stable/api/ssl.html#OpenSSL.SSL.Context.set_tlsext_servername_callback
        ctx.set_tlsext_servername_callback(sniCallback)
        self.socket = SSL.Connection(ctx, socket.socket(self.address_family,self.socket_type))
        self.server_bind()
        self.server_activate()
    
    def shutdown_request(self,request):
        request.shutdown()

class SecureHTTPRequestHandler(SimpleHTTPRequestHandler):
    def setup(self):
        self.connection = self.request
        self.rfile = socket._fileobject(self.request, "rb", self.rbufsize)
        self.wfile = socket._fileobject(self.request, "wb", self.wbufsize)

if __name__ == '__main__':
    ip,port = ('127.0.0.1', 443)
    httpd = SecureHTTPServer((ip, port), SecureHTTPRequestHandler)
    print('Serving HTTPS on {0}:{1}'.format(ip,port))
    httpd.serve_forever()
```

Running this under *Python2* yields the expected result:
```
user:/tmp$ sudo python2 httpsServer.py &
[1] 30968
Serving HTTPS on 127.0.0.1:443
user:/tmp$ curl -s --insecure --key clientPrivateKey.pem --cert clientCertificate.pem https://127.0.0.1 > /dev/null
'sniCallback' called for 127.0.0.1 (conn=<OpenSSL.SSL.Connection object at 0x7f98b97aa4d0>)
'verifyCallback' called for 127.0.0.1 (conn=<OpenSSL.SSL.Connection object at 0x7f98b97aa4d0>,cert=<OpenSSL.crypto.X509 object at 0x7f98b97aa510>,errno=18,depth=0,result=0
'verifyCallback' called for 127.0.0.1 (conn=<OpenSSL.SSL.Connection object at 0x7f98b97aa4d0>,cert=<OpenSSL.crypto.X509 object at 0x7f98b97aa510>,errno=0,depth=0,result=1
127.0.0.1 - - [18/Jun/2019 13:10:36] "GET / HTTP/1.1" 200 -
```

However, under *Python3* the following exception is observed:
```
user:/tmp$ sudo python3 httpsServer.py &
[1] 31064
Serving HTTPS on 127.0.0.1:443
user:/tmp$ curl -s --insecure --key clientPrivateKey.pem --cert clientCertificate.pem https://127.0.0.1 > /dev/null
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 40094)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/http/server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.7/socketserver.py", line 718, in __init__
    self.setup()
  File "httpsServer.py", line 41, in setup
    self.rfile = socket._fileobject(self.request, "rb", self.rbufsize)
AttributeError: module 'socket' has no attribute '_fileobject'
----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/http/server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.7/socketserver.py", line 718, in __init__
    self.setup()
  File "httpsServer.py", line 41, in setup
    self.rfile = socket._fileobject(self.request, "rb", self.rbufsize)
AttributeError: module 'socket' has no attribute '_fileobject'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "httpsServer.py", line 48, in <module>
    httpd.serve_forever()
  File "/usr/lib/python3.7/socketserver.py", line 237, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python3.7/socketserver.py", line 319, in _handle_request_noblock
    self.shutdown_request(request)
  File "httpsServer.py", line 36, in shutdown_request
    request.shutdown()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 2001, in shutdown
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'SSL_shutdown', 'shutdown while in init')]
```

Since the code derives from [HTTPServer](https://docs.python.org/3/library/http.server.html#http.server.HTTPServer) and [SimpleHTTPRequestHandler](https://docs.python.org/3/library/http.server.html#http.server.SimpleHTTPRequestHandler) (which are build-in classes) I expected this to work out-of-the-box. Although certainly I am not hung up on implementing these specific classes; as long as I can serve HTTPS I am content (strong preference on build-in modules).

Please do not suggest using the build-in [ssl module](https://docs.python.org/3/library/ssl.html): my specific use-case requires the verify callback.

P.S.: [Werkzeug](https://pypi.org/project/Werkzeug/) encountered this [issue](https://github.com/pallets/werkzeug/issues/434) as well, resulting in them migrating to the build-in ssl module.

**Comment by alex** [comment]
The `httpsServer.py` code clearly does not support python3, we can't do anything about this.
