### ISSUE TITLE
zlib.error: Error -3 while decompressing data: invalid distance too far back

### ISSUE THREAD

**Issue by zablah** [pyca/pyopenssl#867]
python version 2.7.13

```
python -m OpenSSL
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, rsa
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 14, in <module>
    from cryptography.hazmat.backends.interfaces import RSABackend
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
zlib.error: Error -3 while decompressing data: invalid distance too far back

````

**Comment by zablah** [comment]
I solve this issue by upgrade  setuptools
```
pip install --upgrade setuptools
```
