### ISSUE TITLE
Can't load public key

### ISSUE THREAD

**Issue by eriktelepovsky** [pyca/pyopenssl#951]
Hello.

I am trying to load public key in PEM format but unfortunately I am not able to achieve that :/ Can you help me somebody please?

This is my code:

```Python
from OpenSSL import crypto

certificate = '-----BEGIN PUBLIC KEY-----\n\
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEozvFM1FJP4igUQ6kP8ofnY7ydIWk\n\
sMDk1IKXyr/TRDoX4sTMmmdiIrpmCZD4CLDtP0j2LfD7saSIc8kZUwfILg==\n\
-----END PUBLIC KEY-----'
cert = crypto.load_certificate(crypto.FILETYPE_PEM, certificate)
```

Exception:
```Python
Traceback (most recent call last):
  File "script.py", line 7, in <module>
    cert = crypto.load_certificate(crypto.FILETYPE_PEM, certificate)
  File "/Users/erik/env/crypto/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1794, in load_certificate
    _raise_current_error()
  File "/Users/erik/env/crypto/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('PEM routines', 'get_name', 'no start line')]
```

Any help is appreciated. Thank you very much!

**Comment by tiran** [comment]
You are attempting to load a private key as a certificate. Certificates start with ``BEGIN CERTIFICATE`` or ``BEGIN TRUSTED CERTIFICATE``.

**Comment by eriktelepovsky** [comment]
Thank you for your fast response. When I use load_publickey, I get this exception when I try to verify signed data (that's what I   am trying to achieve actually):

```Python
from OpenSSL import crypto

signature  = b"304502204184d8176ad21fb3edfe7efa4a0524f83d5f2424bce07ac39797c0f767f72d580221009182f61dd3101294109bbfa06259a7d4b6fadcd63c3dc76a5c662319f6e09ed2"
data = b"1234.509781111OK1234561010920141255058df96c2603831046d0e3502cab1ddb7d9b629d7f09a44aee7abbec0be3f2d971"

key = b'-----BEGIN PUBLIC KEY-----\n\
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEozvFM1FJP4igUQ6kP8ofnY7ydIWk\n\
sMDk1IKXyr/TRDoX4sTMmmdiIrpmCZD4CLDtP0j2LfD7saSIc8kZUwfILg==\n\
-----END PUBLIC KEY-----'
# cert = crypto.load_certificate(crypto.FILETYPE_PEM, key)


from OpenSSL.crypto import load_publickey
key = load_publickey(crypto.FILETYPE_PEM, key)
print(key)

try:
    crypto.verify(cert=key, signature=signature, data=data, digest='sha256')
except crypto.Error as exp:
    print('crypto.Error:{}'.format(exp.args))
```

Traceback:
```Python
<OpenSSL.crypto.PKey object at 0x7ff702214860>
Traceback (most recent call last):
  File "script.py", line 18, in <module>
    crypto.verify(cert=key, signature=signature, data=data, digest='sha256')
  File "/Users/erik/env/crypto/lib/python3.7/site-packages/OpenSSL/crypto.py", line 2856, in verify
    pkey = _lib.X509_get_pubkey(cert._x509)
AttributeError: 'PKey' object has no attribute '_x509'
```

**Comment by eriktelepovsky** [comment]
Update:

when I use this:

```Python
x509 = X509()
x509.set_pubkey(key)
crypto.verify(cert=x509, signature=signature, data=data, digest='sha256')
```

I got this exception:

```Python
crypto.Error:([('asn1 encoding routines', 'asn1_check_tlen', 'wrong tag'), ('asn1 encoding routines', 'asn1_item_embed_d2i', 'nested asn1 error')],)
```

Any clues?

**Comment by tiran** [comment]
A public key is not a certificate either. It's a ... public key. :)

PyOpenSSL only handles X.509 certificates and private keys of X.509 certificaes. You have to use PyCA cryptography directly to work with public and private keys, see https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization.html .

**Comment by eriktelepovsky** [comment]
I see. Thank you very much for your fast response and pointing me to the right direction!
