### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SSL_OP_NO_TLSv1_3'

### ISSUE THREAD

**Issue by ShaneHarvey** [pyca/pyopenssl#975]
OpenSSL fails to import with PyPy 2 with pyOpenSSL==20.0.0 and cryptography==3.3.1:

```
(venvpypy2) admin@ip-10-122-15-93:~/tmp$ python
Python 2.7.13 (6abe2e00c51d, Sep 23 2020, 05:06:33)
[PyPy 7.3.2 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import OpenSSL
/home/admin/tmp/venvpypy2/site-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/admin/tmp/venvpypy2/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/admin/tmp/venvpypy2/site-packages/OpenSSL/SSL.py", line 149, in <module>
    OP_NO_TLSv1_3 = _lib.SSL_OP_NO_TLSv1_3
AttributeError: 'module' object has no attribute 'SSL_OP_NO_TLSv1_3'
```

Using the latest versions of pyopenssl and cryptography:
```
(venvpypy2) admin@ip-10-122-15-93:~/tmp$ pip freeze
DEPRECATION: pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
attrs==20.3.0
certifi==2020.12.5
cffi==1.14.2
chardet==3.0.4
cryptography==3.3.1
enum34==1.1.10
greenlet==0.4.13
idna==2.10
ipaddress==1.0.23
pyasn1==0.4.8
pyasn1-modules==0.2.8
-e git+git@github.com:mongodb/mongo-python-driver.git@61232b7f21d8f0ad9023c8ef0912017d062fafc0#egg=pymongo
pyOpenSSL==20.0.0
readline==6.2.4.1
requests==2.25.0
service-identity==18.1.0
six==1.15.0
urllib3==1.26.2
```

openssl version:
```
(venvpypy2) admin@ip-10-122-15-93:~/tmp$ openssl version
OpenSSL 1.1.0f  25 May 2017 (Library: OpenSSL 1.1.0l  10 Sep 2019)
```

Pypy version:
```
(venvpypy2) admin@ip-10-122-15-93:~/tmp$ python --version
Python 2.7.13 (6abe2e00c51d, Sep 23 2020, 05:06:33)
[PyPy 7.3.2 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

This seems like a different issue from: https://github.com/pyca/pyopenssl/issues/973

Edit: I can also reproduce this issue with PyPy 3.6.

**Comment by reaperhulk** [comment]
https://github.com/pyca/pyopenssl/issues/970#issuecomment-743195788 also mentions this. Bug is that pyOpenSSL assumes 1.1.1 when it should assume 1.1.0+. PRs welcome to fix this one!
